export type IconDef = { name: string; category: string; tags: string[] };

export const ICON_DEFINITIONS: IconDef[] = [
  // ─── Technology (30 icons) ───
  { name: 'Laptop', category: 'technology', tags: ['computer', 'device', 'work'] },
  { name: 'Smartphone', category: 'technology', tags: ['phone', 'mobile', 'device'] },
  { name: 'Desktop Monitor', category: 'technology', tags: ['screen', 'display'] },
  { name: 'Server Rack', category: 'technology', tags: ['hosting', 'backend', 'cloud'] },
  { name: 'Wi-Fi Signal', category: 'technology', tags: ['internet', 'wireless'] },
  { name: 'Bluetooth', category: 'technology', tags: ['wireless', 'connect'] },
  { name: 'USB Drive', category: 'technology', tags: ['storage', 'data', 'flash'] },
  { name: 'Microchip', category: 'technology', tags: ['cpu', 'processor', 'hardware'] },
  { name: 'Robot Head', category: 'technology', tags: ['ai', 'bot', 'automation'] },
  { name: 'Code Brackets', category: 'technology', tags: ['programming', 'developer'] },
  { name: 'Terminal Window', category: 'technology', tags: ['command', 'cli', 'shell'] },
  { name: 'Database Cylinder', category: 'technology', tags: ['storage', 'data', 'sql'] },
  { name: 'Cloud Upload', category: 'technology', tags: ['cloud', 'upload'] },
  { name: 'Cloud Download', category: 'technology', tags: ['cloud', 'download'] },
  { name: 'Keyboard', category: 'technology', tags: ['typing', 'input'] },
  { name: 'Mouse Cursor', category: 'technology', tags: ['pointer', 'click'] },
  { name: 'Printer', category: 'technology', tags: ['print', 'document'] },
  { name: 'Webcam', category: 'technology', tags: ['camera', 'video', 'call'] },
  { name: 'Smartwatch', category: 'technology', tags: ['wearable', 'time'] },
  { name: 'VR Headset', category: 'technology', tags: ['virtual', 'reality'] },
  { name: 'Drone', category: 'technology', tags: ['aerial', 'camera', 'flying'] },
  { name: 'Satellite Dish', category: 'technology', tags: ['signal', 'broadcast'] },
  { name: 'Battery Charging', category: 'technology', tags: ['power', 'energy'] },
  { name: 'QR Code', category: 'technology', tags: ['scan', 'code', 'link'] },
  { name: 'Hard Drive', category: 'technology', tags: ['storage', 'disk'] },
  { name: 'Ethernet Cable', category: 'technology', tags: ['network', 'connection'] },
  { name: 'Power Button', category: 'technology', tags: ['on', 'off', 'start'] },
  { name: 'Settings Gear', category: 'technology', tags: ['config', 'options'] },
  { name: 'CPU Fan', category: 'technology', tags: ['cooling', 'hardware'] },
  { name: 'SSD Drive', category: 'technology', tags: ['fast', 'storage', 'nvme'] },

  // ─── Business (25 icons) ───
  { name: 'Briefcase', category: 'business', tags: ['work', 'office'] },
  { name: 'Line Chart Rising', category: 'business', tags: ['growth', 'analytics'] },
  { name: 'Bar Chart', category: 'business', tags: ['statistics', 'data'] },
  { name: 'Pie Chart', category: 'business', tags: ['breakdown', 'percentage'] },
  { name: 'Dollar Sign', category: 'business', tags: ['money', 'currency'] },
  { name: 'Credit Card', category: 'business', tags: ['payment', 'purchase'] },
  { name: 'Wallet', category: 'business', tags: ['money', 'cash'] },
  { name: 'Handshake', category: 'business', tags: ['deal', 'partnership'] },
  { name: 'Presentation Board', category: 'business', tags: ['meeting', 'pitch'] },
  { name: 'Target Bullseye', category: 'business', tags: ['goal', 'aim'] },
  { name: 'Trophy Cup', category: 'business', tags: ['achievement', 'winner'] },
  { name: 'Calendar Schedule', category: 'business', tags: ['date', 'planner'] },
  { name: 'Clock Timer', category: 'business', tags: ['time', 'deadline'] },
  { name: 'Clipboard Checklist', category: 'business', tags: ['tasks', 'todo'] },
  { name: 'Invoice Receipt', category: 'business', tags: ['bill', 'payment'] },
  { name: 'Office Building', category: 'business', tags: ['company', 'corporate'] },
  { name: 'Lightbulb Idea', category: 'business', tags: ['innovation', 'creative'] },
  { name: 'Rocket Launch', category: 'business', tags: ['startup', 'launch'] },
  { name: 'Megaphone', category: 'business', tags: ['marketing', 'announce'] },
  { name: 'Funnel Pipeline', category: 'business', tags: ['sales', 'conversion'] },
  { name: 'Badge Certificate', category: 'business', tags: ['certification', 'award'] },
  { name: 'Coins Stack', category: 'business', tags: ['savings', 'investment'] },
  { name: 'Diamond Gem', category: 'business', tags: ['premium', 'luxury'] },
  { name: 'Stamp Seal', category: 'business', tags: ['approved', 'official'] },
  { name: 'Hourglass', category: 'business', tags: ['time', 'waiting', 'patience'] },

  // ─── Communication (20 icons) ───
  { name: 'Chat Bubble', category: 'communication', tags: ['message', 'talk'] },
  { name: 'Chat Bubbles Double', category: 'communication', tags: ['discussion', 'dialogue'] },
  { name: 'Email Envelope', category: 'communication', tags: ['mail', 'letter'] },
  { name: 'Phone Ringing', category: 'communication', tags: ['call', 'ring'] },
  { name: 'Video Call', category: 'communication', tags: ['camera', 'meeting'] },
  { name: 'Notification Bell', category: 'communication', tags: ['alert', 'reminder'] },
  { name: 'Send Paper Plane', category: 'communication', tags: ['send', 'deliver'] },
  { name: 'Inbox Tray', category: 'communication', tags: ['receive', 'messages'] },
  { name: 'At Symbol', category: 'communication', tags: ['email', 'mention'] },
  { name: 'Link Chain', category: 'communication', tags: ['url', 'connect'] },
  { name: 'Share Network', category: 'communication', tags: ['share', 'distribute'] },
  { name: 'Antenna Broadcast', category: 'communication', tags: ['signal', 'radio'] },
  { name: 'Contact Book', category: 'communication', tags: ['address', 'directory'] },
  { name: 'Emoji Smile', category: 'communication', tags: ['happy', 'emoticon'] },
  { name: 'Emoji Sad', category: 'communication', tags: ['unhappy', 'emoticon'] },
  { name: 'Thumbs Up', category: 'communication', tags: ['like', 'approve'] },
  { name: 'Thumbs Down', category: 'communication', tags: ['dislike', 'reject'] },
  { name: 'Quote Marks', category: 'communication', tags: ['quotation', 'cite'] },
  { name: 'Microphone Voice', category: 'communication', tags: ['speak', 'record'] },
  { name: 'Translate Globe', category: 'communication', tags: ['language', 'translate'] },

  // ─── Nature (25 icons) ───
  { name: 'Sun', category: 'nature', tags: ['sunny', 'weather', 'bright'] },
  { name: 'Moon Crescent', category: 'nature', tags: ['night', 'lunar'] },
  { name: 'Star Five Point', category: 'nature', tags: ['favorite', 'rating'] },
  { name: 'Cloud', category: 'nature', tags: ['sky', 'weather'] },
  { name: 'Rain Drops', category: 'nature', tags: ['weather', 'water'] },
  { name: 'Lightning Bolt', category: 'nature', tags: ['thunder', 'storm'] },
  { name: 'Snowflake', category: 'nature', tags: ['winter', 'cold'] },
  { name: 'Rainbow', category: 'nature', tags: ['color', 'arc'] },
  { name: 'Tree Oak', category: 'nature', tags: ['forest', 'wood'] },
  { name: 'Pine Tree', category: 'nature', tags: ['evergreen', 'forest'] },
  { name: 'Leaf', category: 'nature', tags: ['plant', 'green'] },
  { name: 'Flower Rose', category: 'nature', tags: ['bloom', 'garden'] },
  { name: 'Cactus', category: 'nature', tags: ['desert', 'succulent'] },
  { name: 'Mountain Peak', category: 'nature', tags: ['hiking', 'summit'] },
  { name: 'Ocean Wave', category: 'nature', tags: ['sea', 'water'] },
  { name: 'Flame Fire', category: 'nature', tags: ['hot', 'burn'] },
  { name: 'Water Droplet', category: 'nature', tags: ['liquid', 'rain'] },
  { name: 'Wind Breeze', category: 'nature', tags: ['air', 'blow'] },
  { name: 'Volcano', category: 'nature', tags: ['eruption', 'lava'] },
  { name: 'Globe Earth', category: 'nature', tags: ['world', 'planet'] },
  { name: 'Sunrise Horizon', category: 'nature', tags: ['dawn', 'morning'] },
  { name: 'Mushroom', category: 'nature', tags: ['fungi', 'forest'] },
  { name: 'Seashell', category: 'nature', tags: ['beach', 'ocean'] },
  { name: 'Tornado', category: 'nature', tags: ['storm', 'disaster'] },
  { name: 'Coral Reef', category: 'nature', tags: ['ocean', 'marine'] },

  // ─── Food & Drink (20 icons) ───
  { name: 'Coffee Cup', category: 'food-drink', tags: ['cafe', 'morning'] },
  { name: 'Pizza Slice', category: 'food-drink', tags: ['fast-food', 'italian'] },
  { name: 'Hamburger', category: 'food-drink', tags: ['burger', 'fast-food'] },
  { name: 'Ice Cream Cone', category: 'food-drink', tags: ['dessert', 'sweet'] },
  { name: 'Birthday Cake', category: 'food-drink', tags: ['celebration', 'party'] },
  { name: 'Wine Glass', category: 'food-drink', tags: ['alcohol', 'dining'] },
  { name: 'Beer Mug', category: 'food-drink', tags: ['alcohol', 'pub'] },
  { name: 'Apple Fruit', category: 'food-drink', tags: ['healthy', 'fruit'] },
  { name: 'Cooking Pot', category: 'food-drink', tags: ['kitchen', 'cook'] },
  { name: 'Fork and Knife', category: 'food-drink', tags: ['utensils', 'dining'] },
  { name: 'Sushi Roll', category: 'food-drink', tags: ['japanese', 'seafood'] },
  { name: 'Taco', category: 'food-drink', tags: ['mexican', 'wrap'] },
  { name: 'Cupcake', category: 'food-drink', tags: ['bakery', 'sweet'] },
  { name: 'Hot Dog', category: 'food-drink', tags: ['fast-food', 'snack'] },
  { name: 'Donut', category: 'food-drink', tags: ['pastry', 'sprinkles'] },
  { name: 'Cocktail Glass', category: 'food-drink', tags: ['drink', 'bar'] },
  { name: 'Tea Cup', category: 'food-drink', tags: ['hot', 'herbal'] },
  { name: 'Popcorn Box', category: 'food-drink', tags: ['snack', 'movie'] },
  { name: 'Avocado', category: 'food-drink', tags: ['healthy', 'green'] },
  { name: 'Egg Fried', category: 'food-drink', tags: ['breakfast', 'cooking'] },

  // ─── Health (15 icons) ───
  { name: 'Heart Pulse', category: 'health', tags: ['heartbeat', 'vital'] },
  { name: 'Stethoscope', category: 'health', tags: ['doctor', 'medical'] },
  { name: 'Pill Capsule', category: 'health', tags: ['medicine', 'pharmacy'] },
  { name: 'Syringe Needle', category: 'health', tags: ['injection', 'vaccine'] },
  { name: 'First Aid Kit', category: 'health', tags: ['emergency', 'medical'] },
  { name: 'Hospital Cross', category: 'health', tags: ['medical', 'emergency'] },
  { name: 'DNA Helix', category: 'health', tags: ['genetics', 'biology'] },
  { name: 'Brain', category: 'health', tags: ['mind', 'intelligence'] },
  { name: 'Tooth', category: 'health', tags: ['dental', 'dentist'] },
  { name: 'Eye Vision', category: 'health', tags: ['sight', 'optic'] },
  { name: 'Lungs', category: 'health', tags: ['breathing', 'respiratory'] },
  { name: 'Bandage', category: 'health', tags: ['wound', 'heal'] },
  { name: 'Thermometer', category: 'health', tags: ['temperature', 'fever'] },
  { name: 'Wheelchair', category: 'health', tags: ['accessibility', 'mobility'] },
  { name: 'Ambulance', category: 'health', tags: ['emergency', 'vehicle'] },

  // ─── Education (15 icons) ───
  { name: 'Open Book', category: 'education', tags: ['reading', 'library'] },
  { name: 'Closed Book', category: 'education', tags: ['textbook', 'novel'] },
  { name: 'Graduation Cap', category: 'education', tags: ['degree', 'university'] },
  { name: 'Pencil Writing', category: 'education', tags: ['write', 'draw'] },
  { name: 'School Backpack', category: 'education', tags: ['student', 'bag'] },
  { name: 'Globe Stand', category: 'education', tags: ['geography', 'world'] },
  { name: 'Microscope', category: 'education', tags: ['science', 'lab'] },
  { name: 'Telescope', category: 'education', tags: ['astronomy', 'observe'] },
  { name: 'Calculator', category: 'education', tags: ['math', 'numbers'] },
  { name: 'Test Tube', category: 'education', tags: ['chemistry', 'experiment'] },
  { name: 'Atom Model', category: 'education', tags: ['physics', 'nucleus'] },
  { name: 'Chalkboard', category: 'education', tags: ['classroom', 'teaching'] },
  { name: 'Notebook Spiral', category: 'education', tags: ['notes', 'journal'] },
  { name: 'Ruler Straight', category: 'education', tags: ['measure', 'geometry'] },
  { name: 'Paint Palette', category: 'education', tags: ['art', 'color'] },

  // ─── Travel (15 icons) ───
  { name: 'Airplane', category: 'travel', tags: ['flight', 'plane'] },
  { name: 'Car Sedan', category: 'travel', tags: ['vehicle', 'drive'] },
  { name: 'Train Locomotive', category: 'travel', tags: ['railway', 'transit'] },
  { name: 'Ship Boat', category: 'travel', tags: ['cruise', 'sailing'] },
  { name: 'Bicycle', category: 'travel', tags: ['bike', 'cycling'] },
  { name: 'Bus', category: 'travel', tags: ['transit', 'public'] },
  { name: 'Taxi Cab', category: 'travel', tags: ['ride', 'hire'] },
  { name: 'Compass Direction', category: 'travel', tags: ['navigate', 'explore'] },
  { name: 'Map Pin', category: 'travel', tags: ['location', 'marker'] },
  { name: 'Luggage Suitcase', category: 'travel', tags: ['baggage', 'packing'] },
  { name: 'Passport', category: 'travel', tags: ['id', 'border'] },
  { name: 'Tent Camping', category: 'travel', tags: ['outdoor', 'camp'] },
  { name: 'Beach Umbrella', category: 'travel', tags: ['vacation', 'holiday'] },
  { name: 'Lighthouse', category: 'travel', tags: ['coast', 'beacon'] },
  { name: 'Hot Air Balloon', category: 'travel', tags: ['flying', 'adventure'] },

  // ─── Entertainment (20 icons) ───
  { name: 'Music Note', category: 'entertainment', tags: ['sound', 'melody'] },
  { name: 'Headphones', category: 'entertainment', tags: ['audio', 'listen'] },
  { name: 'Guitar Acoustic', category: 'entertainment', tags: ['instrument', 'string'] },
  { name: 'Microphone Stand', category: 'entertainment', tags: ['sing', 'podcast'] },
  { name: 'Film Camera', category: 'entertainment', tags: ['movie', 'cinema'] },
  { name: 'Photo Camera', category: 'entertainment', tags: ['photography', 'snap'] },
  { name: 'Game Controller', category: 'entertainment', tags: ['gaming', 'console'] },
  { name: 'Dice Pair', category: 'entertainment', tags: ['game', 'chance'] },
  { name: 'Playing Card', category: 'entertainment', tags: ['poker', 'deck'] },
  { name: 'Puzzle Piece', category: 'entertainment', tags: ['solve', 'fit'] },
  { name: 'Theater Masks', category: 'entertainment', tags: ['drama', 'comedy'] },
  { name: 'Paint Brush Art', category: 'entertainment', tags: ['painting', 'creative'] },
  { name: 'Video Play Button', category: 'entertainment', tags: ['play', 'stream'] },
  { name: 'Ticket Stub', category: 'entertainment', tags: ['event', 'concert'] },
  { name: 'Magic Wand', category: 'entertainment', tags: ['wizard', 'fantasy'] },
  { name: 'Crown Royal', category: 'entertainment', tags: ['king', 'premium'] },
  { name: 'Piano Keys', category: 'entertainment', tags: ['instrument', 'play'] },
  { name: 'Drum', category: 'entertainment', tags: ['percussion', 'beat'] },
  { name: 'Clapperboard', category: 'entertainment', tags: ['film', 'director'] },
  { name: 'Vinyl Record', category: 'entertainment', tags: ['music', 'retro'] },

  // ─── Arrows & Navigation (15 icons) ───
  { name: 'Arrow Right', category: 'arrows-navigation', tags: ['next', 'forward'] },
  { name: 'Arrow Left', category: 'arrows-navigation', tags: ['back', 'previous'] },
  { name: 'Arrow Up', category: 'arrows-navigation', tags: ['upload', 'increase'] },
  { name: 'Arrow Down', category: 'arrows-navigation', tags: ['download', 'decrease'] },
  { name: 'Refresh Arrows', category: 'arrows-navigation', tags: ['reload', 'sync'] },
  { name: 'Expand Fullscreen', category: 'arrows-navigation', tags: ['maximize', 'enlarge'] },
  { name: 'Compress Minimize', category: 'arrows-navigation', tags: ['shrink', 'reduce'] },
  { name: 'Menu Hamburger', category: 'arrows-navigation', tags: ['navigation', 'sidebar'] },
  { name: 'Grid View', category: 'arrows-navigation', tags: ['layout', 'tiles'] },
  { name: 'List View', category: 'arrows-navigation', tags: ['layout', 'rows'] },
  { name: 'Search Magnifier', category: 'arrows-navigation', tags: ['find', 'look'] },
  { name: 'Filter Funnel', category: 'arrows-navigation', tags: ['sort', 'refine'] },
  { name: 'Sort Lines', category: 'arrows-navigation', tags: ['order', 'arrange'] },
  { name: 'Home House', category: 'arrows-navigation', tags: ['main', 'dashboard'] },
  { name: 'Cross Close', category: 'arrows-navigation', tags: ['close', 'remove'] },

  // ─── Security (12 icons) ───
  { name: 'Lock Closed', category: 'security', tags: ['secure', 'locked'] },
  { name: 'Lock Open', category: 'security', tags: ['unlock', 'access'] },
  { name: 'Key', category: 'security', tags: ['access', 'password'] },
  { name: 'Shield Check', category: 'security', tags: ['protection', 'verified'] },
  { name: 'Shield Warning', category: 'security', tags: ['alert', 'caution'] },
  { name: 'Eye Visible', category: 'security', tags: ['show', 'watch'] },
  { name: 'Eye Hidden', category: 'security', tags: ['hide', 'private'] },
  { name: 'Alarm Siren', category: 'security', tags: ['warning', 'emergency'] },
  { name: 'CCTV Camera', category: 'security', tags: ['surveillance', 'monitor'] },
  { name: 'Bug Insect', category: 'security', tags: ['debug', 'error'] },
  { name: 'Firewall Brick', category: 'security', tags: ['protection', 'network'] },
  { name: 'Incognito Hat', category: 'security', tags: ['private', 'anonymous'] },

  // ─── Files & Documents (12 icons) ───
  { name: 'File Document', category: 'files-documents', tags: ['doc', 'page'] },
  { name: 'File PDF', category: 'files-documents', tags: ['pdf', 'export'] },
  { name: 'File Image', category: 'files-documents', tags: ['photo', 'media'] },
  { name: 'File Code', category: 'files-documents', tags: ['source', 'script'] },
  { name: 'Folder Closed', category: 'files-documents', tags: ['directory', 'organize'] },
  { name: 'Folder Open', category: 'files-documents', tags: ['directory', 'browse'] },
  { name: 'Zip Archive', category: 'files-documents', tags: ['compress', 'archive'] },
  { name: 'Trash Can', category: 'files-documents', tags: ['delete', 'remove'] },
  { name: 'Download Arrow', category: 'files-documents', tags: ['save', 'export'] },
  { name: 'Upload Arrow', category: 'files-documents', tags: ['upload', 'import'] },
  { name: 'Copy Duplicate', category: 'files-documents', tags: ['clone', 'paste'] },
  { name: 'Floppy Save', category: 'files-documents', tags: ['save', 'store'] },

  // ─── Social Media (10 icons) ───
  { name: 'Heart Like', category: 'social-media', tags: ['love', 'favorite'] },
  { name: 'Bookmark Flag', category: 'social-media', tags: ['save', 'later'] },
  { name: 'User Profile', category: 'social-media', tags: ['account', 'avatar'] },
  { name: 'Users Group', category: 'social-media', tags: ['team', 'community'] },
  { name: 'Hashtag', category: 'social-media', tags: ['tag', 'trending'] },
  { name: 'Camera Selfie', category: 'social-media', tags: ['photo', 'story'] },
  { name: 'Live Dot', category: 'social-media', tags: ['broadcast', 'streaming'] },
  { name: 'Follow Plus', category: 'social-media', tags: ['add', 'follow'] },
  { name: 'Verified Check', category: 'social-media', tags: ['official', 'trusted'] },
  { name: 'Share Curved Arrow', category: 'social-media', tags: ['repost', 'forward'] },

  // ─── Design Tools (10 icons) ───
  { name: 'Color Palette', category: 'design-tools', tags: ['colors', 'paint'] },
  { name: 'Pen Tool', category: 'design-tools', tags: ['vector', 'bezier'] },
  { name: 'Crop Frame', category: 'design-tools', tags: ['resize', 'trim'] },
  { name: 'Layers Stack', category: 'design-tools', tags: ['layer', 'stack'] },
  { name: 'Eyedropper', category: 'design-tools', tags: ['color', 'pick'] },
  { name: 'Grid Layout', category: 'design-tools', tags: ['align', 'grid'] },
  { name: 'Typography A', category: 'design-tools', tags: ['font', 'text'] },
  { name: 'Ruler Measure', category: 'design-tools', tags: ['dimension', 'size'] },
  { name: 'Eraser', category: 'design-tools', tags: ['remove', 'clean'] },
  { name: 'Shapes Circle', category: 'design-tools', tags: ['shape', 'circle'] },
];
