export type IconDef = { name: string; category: string; tags: string[] };

export const ICON_DEFINITIONS: IconDef[] = [
  // ─── Technology (30 icons) ───
  { name: 'Laptop', category: 'technology', tags: ['computer', 'device', 'work'] },
  { name: 'Smartphone', category: 'technology', tags: ['phone', 'mobile', 'device'] },
  { name: 'Desktop Monitor', category: 'technology', tags: ['screen', 'display'] },
  { name: 'Server Rack', category: 'technology', tags: ['hosting', 'backend', 'cloud'] },
  { name: 'Wi-Fi Signal', category: 'technology', tags: ['internet', 'wireless'] },
  { name: 'Bluetooth', category: 'technology', tags: ['wireless', 'connect'] },
  { name: 'USB Drive', category: 'technology', tags: ['storage', 'data', 'flash'] },
  { name: 'Microchip', category: 'technology', tags: ['cpu', 'processor', 'hardware'] },
  { name: 'Robot Head', category: 'technology', tags: ['ai', 'bot', 'automation'] },
  { name: 'Code Brackets', category: 'technology', tags: ['programming', 'developer'] },
  { name: 'Terminal Window', category: 'technology', tags: ['command', 'cli', 'shell'] },
  { name: 'Database Cylinder', category: 'technology', tags: ['storage', 'data', 'sql'] },
  { name: 'Cloud Upload', category: 'technology', tags: ['cloud', 'upload'] },
  { name: 'Cloud Download', category: 'technology', tags: ['cloud', 'download'] },
  { name: 'Keyboard', category: 'technology', tags: ['typing', 'input'] },
  { name: 'Mouse Cursor', category: 'technology', tags: ['pointer', 'click'] },
  { name: 'Printer', category: 'technology', tags: ['print', 'document'] },
  { name: 'Webcam', category: 'technology', tags: ['camera', 'video', 'call'] },
  { name: 'Smartwatch', category: 'technology', tags: ['wearable', 'time'] },
  { name: 'VR Headset', category: 'technology', tags: ['virtual', 'reality'] },
  { name: 'Drone', category: 'technology', tags: ['aerial', 'camera', 'flying'] },
  { name: 'Satellite Dish', category: 'technology', tags: ['signal', 'broadcast'] },
  { name: 'Battery Charging', category: 'technology', tags: ['power', 'energy'] },
  { name: 'QR Code', category: 'technology', tags: ['scan', 'code', 'link'] },
  { name: 'Hard Drive', category: 'technology', tags: ['storage', 'disk'] },
  { name: 'Ethernet Cable', category: 'technology', tags: ['network', 'connection'] },
  { name: 'Power Button', category: 'technology', tags: ['on', 'off', 'start'] },
  { name: 'Settings Gear', category: 'technology', tags: ['config', 'options'] },
  { name: 'CPU Fan', category: 'technology', tags: ['cooling', 'hardware'] },
  { name: 'SSD Drive', category: 'technology', tags: ['fast', 'storage', 'nvme'] },

  // ─── Business (25 icons) ───
  { name: 'Briefcase', category: 'business', tags: ['work', 'office'] },
  { name: 'Line Chart Rising', category: 'business', tags: ['growth', 'analytics'] },
  { name: 'Bar Chart', category: 'business', tags: ['statistics', 'data'] },
  { name: 'Pie Chart', category: 'business', tags: ['breakdown', 'percentage'] },
  { name: 'Dollar Sign', category: 'business', tags: ['money', 'currency'] },
  { name: 'Credit Card', category: 'business', tags: ['payment', 'purchase'] },
  { name: 'Wallet', category: 'business', tags: ['money', 'cash'] },
  { name: 'Handshake', category: 'business', tags: ['deal', 'partnership'] },
  { name: 'Presentation Board', category: 'business', tags: ['meeting', 'pitch'] },
  { name: 'Target Bullseye', category: 'business', tags: ['goal', 'aim'] },
  { name: 'Trophy Cup', category: 'business', tags: ['achievement', 'winner'] },
  { name: 'Calendar Schedule', category: 'business', tags: ['date', 'planner'] },
  { name: 'Clock Timer', category: 'business', tags: ['time', 'deadline'] },
  { name: 'Clipboard Checklist', category: 'business', tags: ['tasks', 'todo'] },
  { name: 'Invoice Receipt', category: 'business', tags: ['bill', 'payment'] },
  { name: 'Office Building', category: 'business', tags: ['company', 'corporate'] },
  { name: 'Lightbulb Idea', category: 'business', tags: ['innovation', 'creative'] },
  { name: 'Rocket Launch', category: 'business', tags: ['startup', 'launch'] },
  { name: 'Megaphone', category: 'business', tags: ['marketing', 'announce'] },
  { name: 'Funnel Pipeline', category: 'business', tags: ['sales', 'conversion'] },
  { name: 'Badge Certificate', category: 'business', tags: ['certification', 'award'] },
  { name: 'Coins Stack', category: 'business', tags: ['savings', 'investment'] },
  { name: 'Diamond Gem', category: 'business', tags: ['premium', 'luxury'] },
  { name: 'Stamp Seal', category: 'business', tags: ['approved', 'official'] },
  { name: 'Hourglass', category: 'business', tags: ['time', 'waiting', 'patience'] },

  // ─── Communication (20 icons) ───
  { name: 'Chat Bubble', category: 'communication', tags: ['message', 'talk'] },
  { name: 'Chat Bubbles Double', category: 'communication', tags: ['discussion', 'dialogue'] },
  { name: 'Email Envelope', category: 'communication', tags: ['mail', 'letter'] },
  { name: 'Phone Ringing', category: 'communication', tags: ['call', 'ring'] },
  { name: 'Video Call', category: 'communication', tags: ['camera', 'meeting'] },
  { name: 'Notification Bell', category: 'communication', tags: ['alert', 'reminder'] },
  { name: 'Send Paper Plane', category: 'communication', tags: ['send', 'deliver'] },
  { name: 'Inbox Tray', category: 'communication', tags: ['receive', 'messages'] },
  { name: 'At Symbol', category: 'communication', tags: ['email', 'mention'] },
  { name: 'Link Chain', category: 'communication', tags: ['url', 'connect'] },
  { name: 'Share Network', category: 'communication', tags: ['share', 'distribute'] },
  { name: 'Antenna Broadcast', category: 'communication', tags: ['signal', 'radio'] },
  { name: 'Contact Book', category: 'communication', tags: ['address', 'directory'] },
  { name: 'Emoji Smile', category: 'communication', tags: ['happy', 'emoticon'] },
  { name: 'Emoji Sad', category: 'communication', tags: ['unhappy', 'emoticon'] },
  { name: 'Thumbs Up', category: 'communication', tags: ['like', 'approve'] },
  { name: 'Thumbs Down', category: 'communication', tags: ['dislike', 'reject'] },
  { name: 'Quote Marks', category: 'communication', tags: ['quotation', 'cite'] },
  { name: 'Microphone Voice', category: 'communication', tags: ['speak', 'record'] },
  { name: 'Translate Globe', category: 'communication', tags: ['language', 'translate'] },

  // ─── Nature (25 icons) ───
  { name: 'Sun', category: 'nature', tags: ['sunny', 'weather', 'bright'] },
  { name: 'Moon Crescent', category: 'nature', tags: ['night', 'lunar'] },
  { name: 'Star Five Point', category: 'nature', tags: ['favorite', 'rating'] },
  { name: 'Cloud', category: 'nature', tags: ['sky', 'weather'] },
  { name: 'Rain Drops', category: 'nature', tags: ['weather', 'water'] },
  { name: 'Lightning Bolt', category: 'nature', tags: ['thunder', 'storm'] },
  { name: 'Snowflake', category: 'nature', tags: ['winter', 'cold'] },
  { name: 'Rainbow', category: 'nature', tags: ['color', 'arc'] },
  { name: 'Tree Oak', category: 'nature', tags: ['forest', 'wood'] },
  { name: 'Pine Tree', category: 'nature', tags: ['evergreen', 'forest'] },
  { name: 'Leaf', category: 'nature', tags: ['plant', 'green'] },
  { name: 'Flower Rose', category: 'nature', tags: ['bloom', 'garden'] },
  { name: 'Cactus', category: 'nature', tags: ['desert', 'succulent'] },
  { name: 'Mountain Peak', category: 'nature', tags: ['hiking', 'summit'] },
  { name: 'Ocean Wave', category: 'nature', tags: ['sea', 'water'] },
  { name: 'Flame Fire', category: 'nature', tags: ['hot', 'burn'] },
  { name: 'Water Droplet', category: 'nature', tags: ['liquid', 'rain'] },
  { name: 'Wind Breeze', category: 'nature', tags: ['air', 'blow'] },
  { name: 'Volcano', category: 'nature', tags: ['eruption', 'lava'] },
  { name: 'Globe Earth', category: 'nature', tags: ['world', 'planet'] },
  { name: 'Sunrise Horizon', category: 'nature', tags: ['dawn', 'morning'] },
  { name: 'Mushroom', category: 'nature', tags: ['fungi', 'forest'] },
  { name: 'Seashell', category: 'nature', tags: ['beach', 'ocean'] },
  { name: 'Tornado', category: 'nature', tags: ['storm', 'disaster'] },
  { name: 'Coral Reef', category: 'nature', tags: ['ocean', 'marine'] },

  // ─── Food & Drink (20 icons) ───
  { name: 'Coffee Cup', category: 'food-drink', tags: ['cafe', 'morning'] },
  { name: 'Pizza Slice', category: 'food-drink', tags: ['fast-food', 'italian'] },
  { name: 'Hamburger', category: 'food-drink', tags: ['burger', 'fast-food'] },
  { name: 'Ice Cream Cone', category: 'food-drink', tags: ['dessert', 'sweet'] },
  { name: 'Birthday Cake', category: 'food-drink', tags: ['celebration', 'party'] },
  { name: 'Wine Glass', category: 'food-drink', tags: ['alcohol', 'dining'] },
  { name: 'Beer Mug', category: 'food-drink', tags: ['alcohol', 'pub'] },
  { name: 'Apple Fruit', category: 'food-drink', tags: ['healthy', 'fruit'] },
  { name: 'Cooking Pot', category: 'food-drink', tags: ['kitchen', 'cook'] },
  { name: 'Fork and Knife', category: 'food-drink', tags: ['utensils', 'dining'] },
  { name: 'Sushi Roll', category: 'food-drink', tags: ['japanese', 'seafood'] },
  { name: 'Taco', category: 'food-drink', tags: ['mexican', 'wrap'] },
  { name: 'Cupcake', category: 'food-drink', tags: ['bakery', 'sweet'] },
  { name: 'Hot Dog', category: 'food-drink', tags: ['fast-food', 'snack'] },
  { name: 'Donut', category: 'food-drink', tags: ['pastry', 'sprinkles'] },
  { name: 'Cocktail Glass', category: 'food-drink', tags: ['drink', 'bar'] },
  { name: 'Tea Cup', category: 'food-drink', tags: ['hot', 'herbal'] },
  { name: 'Popcorn Box', category: 'food-drink', tags: ['snack', 'movie'] },
  { name: 'Avocado', category: 'food-drink', tags: ['healthy', 'green'] },
  { name: 'Egg Fried', category: 'food-drink', tags: ['breakfast', 'cooking'] },

  // ─── Health (15 icons) ───
  { name: 'Heart Pulse', category: 'health', tags: ['heartbeat', 'vital'] },
  { name: 'Stethoscope', category: 'health', tags: ['doctor', 'medical'] },
  { name: 'Pill Capsule', category: 'health', tags: ['medicine', 'pharmacy'] },
  { name: 'Syringe Needle', category: 'health', tags: ['injection', 'vaccine'] },
  { name: 'First Aid Kit', category: 'health', tags: ['emergency', 'medical'] },
  { name: 'Hospital Cross', category: 'health', tags: ['medical', 'emergency'] },
  { name: 'DNA Helix', category: 'health', tags: ['genetics', 'biology'] },
  { name: 'Brain', category: 'health', tags: ['mind', 'intelligence'] },
  { name: 'Tooth', category: 'health', tags: ['dental', 'dentist'] },
  { name: 'Eye Vision', category: 'health', tags: ['sight', 'optic'] },
  { name: 'Lungs', category: 'health', tags: ['breathing', 'respiratory'] },
  { name: 'Bandage', category: 'health', tags: ['wound', 'heal'] },
  { name: 'Thermometer', category: 'health', tags: ['temperature', 'fever'] },
  { name: 'Wheelchair', category: 'health', tags: ['accessibility', 'mobility'] },
  { name: 'Ambulance', category: 'health', tags: ['emergency', 'vehicle'] },

  // ─── Education (15 icons) ───
  { name: 'Open Book', category: 'education', tags: ['reading', 'library'] },
  { name: 'Closed Book', category: 'education', tags: ['textbook', 'novel'] },
  { name: 'Graduation Cap', category: 'education', tags: ['degree', 'university'] },
  { name: 'Pencil Writing', category: 'education', tags: ['write', 'draw'] },
  { name: 'School Backpack', category: 'education', tags: ['student', 'bag'] },
  { name: 'Globe Stand', category: 'education', tags: ['geography', 'world'] },
  { name: 'Microscope', category: 'education', tags: ['science', 'lab'] },
  { name: 'Telescope', category: 'education', tags: ['astronomy', 'observe'] },
  { name: 'Calculator', category: 'education', tags: ['math', 'numbers'] },
  { name: 'Test Tube', category: 'education', tags: ['chemistry', 'experiment'] },
  { name: 'Atom Model', category: 'education', tags: ['physics', 'nucleus'] },
  { name: 'Chalkboard', category: 'education', tags: ['classroom', 'teaching'] },
  { name: 'Notebook Spiral', category: 'education', tags: ['notes', 'journal'] },
  { name: 'Ruler Straight', category: 'education', tags: ['measure', 'geometry'] },
  { name: 'Paint Palette', category: 'education', tags: ['art', 'color'] },

  // ─── Travel (15 icons) ───
  { name: 'Airplane', category: 'travel', tags: ['flight', 'plane'] },
  { name: 'Car Sedan', category: 'travel', tags: ['vehicle', 'drive'] },
  { name: 'Train Locomotive', category: 'travel', tags: ['railway', 'transit'] },
  { name: 'Ship Boat', category: 'travel', tags: ['cruise', 'sailing'] },
  { name: 'Bicycle', category: 'travel', tags: ['bike', 'cycling'] },
  { name: 'Bus', category: 'travel', tags: ['transit', 'public'] },
  { name: 'Taxi Cab', category: 'travel', tags: ['ride', 'hire'] },
  { name: 'Compass Direction', category: 'travel', tags: ['navigate', 'explore'] },
  { name: 'Map Pin', category: 'travel', tags: ['location', 'marker'] },
  { name: 'Luggage Suitcase', category: 'travel', tags: ['baggage', 'packing'] },
  { name: 'Passport', category: 'travel', tags: ['id', 'border'] },
  { name: 'Tent Camping', category: 'travel', tags: ['outdoor', 'camp'] },
  { name: 'Beach Umbrella', category: 'travel', tags: ['vacation', 'holiday'] },
  { name: 'Lighthouse', category: 'travel', tags: ['coast', 'beacon'] },
  { name: 'Hot Air Balloon', category: 'travel', tags: ['flying', 'adventure'] },

  // ─── Entertainment (20 icons) ───
  { name: 'Music Note', category: 'entertainment', tags: ['sound', 'melody'] },
  { name: 'Headphones', category: 'entertainment', tags: ['audio', 'listen'] },
  { name: 'Guitar Acoustic', category: 'entertainment', tags: ['instrument', 'string'] },
  { name: 'Microphone Stand', category: 'entertainment', tags: ['sing', 'podcast'] },
  { name: 'Film Camera', category: 'entertainment', tags: ['movie', 'cinema'] },
  { name: 'Photo Camera', category: 'entertainment', tags: ['photography', 'snap'] },
  { name: 'Game Controller', category: 'entertainment', tags: ['gaming', 'console'] },
  { name: 'Dice Pair', category: 'entertainment', tags: ['game', 'chance'] },
  { name: 'Playing Card', category: 'entertainment', tags: ['poker', 'deck'] },
  { name: 'Puzzle Piece', category: 'entertainment', tags: ['solve', 'fit'] },
  { name: 'Theater Masks', category: 'entertainment', tags: ['drama', 'comedy'] },
  { name: 'Paint Brush Art', category: 'entertainment', tags: ['painting', 'creative'] },
  { name: 'Video Play Button', category: 'entertainment', tags: ['play', 'stream'] },
  { name: 'Ticket Stub', category: 'entertainment', tags: ['event', 'concert'] },
  { name: 'Magic Wand', category: 'entertainment', tags: ['wizard', 'fantasy'] },
  { name: 'Crown Royal', category: 'entertainment', tags: ['king', 'premium'] },
  { name: 'Piano Keys', category: 'entertainment', tags: ['instrument', 'play'] },
  { name: 'Drum', category: 'entertainment', tags: ['percussion', 'beat'] },
  { name: 'Clapperboard', category: 'entertainment', tags: ['film', 'director'] },
  { name: 'Vinyl Record', category: 'entertainment', tags: ['music', 'retro'] },

  // ─── Arrows & Navigation (15 icons) ───
  { name: 'Arrow Right', category: 'arrows-navigation', tags: ['next', 'forward'] },
  { name: 'Arrow Left', category: 'arrows-navigation', tags: ['back', 'previous'] },
  { name: 'Arrow Up', category: 'arrows-navigation', tags: ['upload', 'increase'] },
  { name: 'Arrow Down', category: 'arrows-navigation', tags: ['download', 'decrease'] },
  { name: 'Refresh Arrows', category: 'arrows-navigation', tags: ['reload', 'sync'] },
  { name: 'Expand Fullscreen', category: 'arrows-navigation', tags: ['maximize', 'enlarge'] },
  { name: 'Compress Minimize', category: 'arrows-navigation', tags: ['shrink', 'reduce'] },
  { name: 'Menu Hamburger', category: 'arrows-navigation', tags: ['navigation', 'sidebar'] },
  { name: 'Grid View', category: 'arrows-navigation', tags: ['layout', 'tiles'] },
  { name: 'List View', category: 'arrows-navigation', tags: ['layout', 'rows'] },
  { name: 'Search Magnifier', category: 'arrows-navigation', tags: ['find', 'look'] },
  { name: 'Filter Funnel', category: 'arrows-navigation', tags: ['sort', 'refine'] },
  { name: 'Sort Lines', category: 'arrows-navigation', tags: ['order', 'arrange'] },
  { name: 'Home House', category: 'arrows-navigation', tags: ['main', 'dashboard'] },
  { name: 'Cross Close', category: 'arrows-navigation', tags: ['close', 'remove'] },

  // ─── Security (12 icons) ───
  { name: 'Lock Closed', category: 'security', tags: ['secure', 'locked'] },
  { name: 'Lock Open', category: 'security', tags: ['unlock', 'access'] },
  { name: 'Key', category: 'security', tags: ['access', 'password'] },
  { name: 'Shield Check', category: 'security', tags: ['protection', 'verified'] },
  { name: 'Shield Warning', category: 'security', tags: ['alert', 'caution'] },
  { name: 'Eye Visible', category: 'security', tags: ['show', 'watch'] },
  { name: 'Eye Hidden', category: 'security', tags: ['hide', 'private'] },
  { name: 'Alarm Siren', category: 'security', tags: ['warning', 'emergency'] },
  { name: 'CCTV Camera', category: 'security', tags: ['surveillance', 'monitor'] },
  { name: 'Bug Insect', category: 'security', tags: ['debug', 'error'] },
  { name: 'Firewall Brick', category: 'security', tags: ['protection', 'network'] },
  { name: 'Incognito Hat', category: 'security', tags: ['private', 'anonymous'] },

  // ─── Files & Documents (12 icons) ───
  { name: 'File Document', category: 'files-documents', tags: ['doc', 'page'] },
  { name: 'File PDF', category: 'files-documents', tags: ['pdf', 'export'] },
  { name: 'File Image', category: 'files-documents', tags: ['photo', 'media'] },
  { name: 'File Code', category: 'files-documents', tags: ['source', 'script'] },
  { name: 'Folder Closed', category: 'files-documents', tags: ['directory', 'organize'] },
  { name: 'Folder Open', category: 'files-documents', tags: ['directory', 'browse'] },
  { name: 'Zip Archive', category: 'files-documents', tags: ['compress', 'archive'] },
  { name: 'Trash Can', category: 'files-documents', tags: ['delete', 'remove'] },
  { name: 'Download Arrow', category: 'files-documents', tags: ['save', 'export'] },
  { name: 'Upload Arrow', category: 'files-documents', tags: ['upload', 'import'] },
  { name: 'Copy Duplicate', category: 'files-documents', tags: ['clone', 'paste'] },
  { name: 'Floppy Save', category: 'files-documents', tags: ['save', 'store'] },

  // ─── Social Media (10 icons) ───
  { name: 'Heart Like', category: 'social-media', tags: ['love', 'favorite'] },
  { name: 'Bookmark Flag', category: 'social-media', tags: ['save', 'later'] },
  { name: 'User Profile', category: 'social-media', tags: ['account', 'avatar'] },
  { name: 'Users Group', category: 'social-media', tags: ['team', 'community'] },
  { name: 'Hashtag', category: 'social-media', tags: ['tag', 'trending'] },
  { name: 'Camera Selfie', category: 'social-media', tags: ['photo', 'story'] },
  { name: 'Live Dot', category: 'social-media', tags: ['broadcast', 'streaming'] },
  { name: 'Follow Plus', category: 'social-media', tags: ['add', 'follow'] },
  { name: 'Verified Check', category: 'social-media', tags: ['official', 'trusted'] },
  { name: 'Share Curved Arrow', category: 'social-media', tags: ['repost', 'forward'] },

  // ─── Design Tools (10 icons) ───
  { name: 'Color Palette', category: 'design-tools', tags: ['colors', 'paint'] },
  { name: 'Pen Tool', category: 'design-tools', tags: ['vector', 'bezier'] },
  { name: 'Crop Frame', category: 'design-tools', tags: ['resize', 'trim'] },
  { name: 'Layers Stack', category: 'design-tools', tags: ['layer', 'stack'] },
  { name: 'Eyedropper', category: 'design-tools', tags: ['color', 'pick'] },
  { name: 'Grid Layout', category: 'design-tools', tags: ['align', 'grid'] },
  { name: 'Typography A', category: 'design-tools', tags: ['font', 'text'] },
  { name: 'Ruler Measure', category: 'design-tools', tags: ['dimension', 'size'] },
  { name: 'Eraser', category: 'design-tools', tags: ['remove', 'clean'] },
  { name: 'Shapes Circle', category: 'design-tools', tags: ['shape', 'circle'] },

  // ─── Technology Extended (20 icons) ───
  { name: 'Cloud Storage', category: 'technology', tags: ['cloud', 'files', 'backup'] },
  { name: 'API Endpoint', category: 'technology', tags: ['api', 'rest', 'web'] },
  { name: 'Git Branch', category: 'technology', tags: ['version', 'control', 'code'] },
  { name: 'Docker Container', category: 'technology', tags: ['container', 'deploy', 'devops'] },
  { name: 'Package Module', category: 'technology', tags: ['npm', 'library', 'module'] },
  { name: 'Bug Report', category: 'technology', tags: ['debug', 'error', 'issue'] },
  { name: 'Pull Request', category: 'technology', tags: ['code', 'review', 'merge'] },
  { name: 'Code Fork', category: 'technology', tags: ['fork', 'branch', 'git'] },
  { name: 'Monitor Dashboard', category: 'technology', tags: ['screen', 'analytics', 'metrics'] },
  { name: 'Network Graph', category: 'technology', tags: ['nodes', 'topology', 'connect'] },
  { name: 'Firewall', category: 'technology', tags: ['security', 'network', 'protect'] },
  { name: 'Load Balancer', category: 'technology', tags: ['traffic', 'distribute', 'server'] },
  { name: 'Memory RAM', category: 'technology', tags: ['hardware', 'memory', 'compute'] },
  { name: 'GPU Card', category: 'technology', tags: ['graphics', 'hardware', 'render'] },
  { name: 'IoT Sensor', category: 'technology', tags: ['sensor', 'iot', 'device'] },
  { name: 'AR Glasses', category: 'technology', tags: ['augmented', 'reality', 'wearable'] },
  { name: 'NFC Tag', category: 'technology', tags: ['nfc', 'tap', 'wireless'] },
  { name: 'Touchscreen', category: 'technology', tags: ['touch', 'gesture', 'input'] },
  { name: 'Projector Screen', category: 'technology', tags: ['present', 'display', 'meeting'] },
  { name: 'Raspberry Pi', category: 'technology', tags: ['single-board', 'maker', 'iot'] },

  // ─── Business Extended (15 icons) ───
  { name: 'Org Chart', category: 'business', tags: ['hierarchy', 'team', 'structure'] },
  { name: 'Kanban Board', category: 'business', tags: ['agile', 'project', 'tasks'] },
  { name: 'Email Campaign', category: 'business', tags: ['marketing', 'newsletter', 'reach'] },
  { name: 'Customer Support', category: 'business', tags: ['help', 'service', 'assist'] },
  { name: 'Analytics Report', category: 'business', tags: ['data', 'insights', 'report'] },
  { name: 'Survey Form', category: 'business', tags: ['feedback', 'poll', 'questionnaire'] },
  { name: 'Workflow Arrow', category: 'business', tags: ['process', 'flow', 'pipeline'] },
  { name: 'Team Meeting', category: 'business', tags: ['collaborate', 'group', 'discussion'] },
  { name: 'Growth Trend', category: 'business', tags: ['increase', 'progress', 'kpi'] },
  { name: 'Risk Warning', category: 'business', tags: ['alert', 'caution', 'compliance'] },
  { name: 'Contract Document', category: 'business', tags: ['legal', 'sign', 'agreement'] },
  { name: 'Partnership Puzzle', category: 'business', tags: ['connect', 'join', 'integrate'] },
  { name: 'Budget Forecast', category: 'business', tags: ['finance', 'plan', 'projection'] },
  { name: 'Subscription Plan', category: 'business', tags: ['recurring', 'service', 'tier'] },
  { name: 'Milestone Flag', category: 'business', tags: ['goal', 'checkpoint', 'achieve'] },

  // ─── Communication Extended (15 icons) ───
  { name: 'Voice Message', category: 'communication', tags: ['audio', 'record', 'note'] },
  { name: 'Group Chat', category: 'communication', tags: ['team', 'channel', 'thread'] },
  { name: 'Read Receipt', category: 'communication', tags: ['seen', 'delivered', 'status'] },
  { name: 'Reply Arrow', category: 'communication', tags: ['respond', 'answer', 'chat'] },
  { name: 'Forward Message', category: 'communication', tags: ['resend', 'share', 'relay'] },
  { name: 'Mute Bell', category: 'communication', tags: ['silence', 'off', 'notification'] },
  { name: 'Live Stream', category: 'communication', tags: ['broadcast', 'realtime', 'video'] },
  { name: 'Podcast Wave', category: 'communication', tags: ['audio', 'show', 'episode'] },
  { name: 'Feedback Star', category: 'communication', tags: ['rating', 'review', 'opinion'] },
  { name: 'Broadcast Tower', category: 'communication', tags: ['signal', 'transmit', 'coverage'] },
  { name: 'Chat Bot', category: 'communication', tags: ['ai', 'bot', 'assistant'] },
  { name: 'News Feed', category: 'communication', tags: ['updates', 'articles', 'timeline'] },
  { name: 'Mention Tag', category: 'communication', tags: ['at', 'notify', 'reference'] },
  { name: 'Pin Message', category: 'communication', tags: ['important', 'highlight', 'save'] },
  { name: 'Emoji Reaction', category: 'communication', tags: ['react', 'express', 'emotion'] },

  // ─── Nature Extended (20 icons) ───
  { name: 'Bamboo Stalk', category: 'nature', tags: ['tropical', 'plant', 'zen'] },
  { name: 'Cherry Blossom', category: 'nature', tags: ['spring', 'japanese', 'flower'] },
  { name: 'Sunflower', category: 'nature', tags: ['flower', 'garden', 'yellow'] },
  { name: 'Palm Tree', category: 'nature', tags: ['tropical', 'beach', 'summer'] },
  { name: 'Fern Plant', category: 'nature', tags: ['forest', 'green', 'plant'] },
  { name: 'Acorn Nut', category: 'nature', tags: ['autumn', 'oak', 'seed'] },
  { name: 'Frost Ice', category: 'nature', tags: ['cold', 'winter', 'freeze'] },
  { name: 'Fog Mist', category: 'nature', tags: ['weather', 'morning', 'haze'] },
  { name: 'Hailstorm', category: 'nature', tags: ['weather', 'storm', 'ice'] },
  { name: 'Drizzle Rain', category: 'nature', tags: ['light', 'rain', 'wet'] },
  { name: 'Sand Dune', category: 'nature', tags: ['desert', 'arid', 'hot'] },
  { name: 'Cliff Edge', category: 'nature', tags: ['rock', 'coast', 'height'] },
  { name: 'Waterfall', category: 'nature', tags: ['water', 'cascade', 'nature'] },
  { name: 'Hot Spring', category: 'nature', tags: ['water', 'thermal', 'steam'] },
  { name: 'Comet Meteor', category: 'nature', tags: ['space', 'astronomy', 'streak'] },
  { name: 'Northern Lights', category: 'nature', tags: ['aurora', 'sky', 'glow'] },
  { name: 'Eclipse Solar', category: 'nature', tags: ['astronomy', 'moon', 'sun'] },
  { name: 'Pebble Stone', category: 'nature', tags: ['rock', 'zen', 'natural'] },
  { name: 'Crystal Gem', category: 'nature', tags: ['mineral', 'stone', 'shiny'] },
  { name: 'Feather Quill', category: 'nature', tags: ['bird', 'light', 'write'] },

  // ─── Food & Drink Extended (15 icons) ───
  { name: 'Ramen Bowl', category: 'food-drink', tags: ['japanese', 'noodle', 'soup'] },
  { name: 'Steak Meat', category: 'food-drink', tags: ['beef', 'grill', 'dinner'] },
  { name: 'Salad Bowl', category: 'food-drink', tags: ['healthy', 'vegetable', 'fresh'] },
  { name: 'Croissant', category: 'food-drink', tags: ['french', 'bakery', 'breakfast'] },
  { name: 'Bento Box', category: 'food-drink', tags: ['lunch', 'japanese', 'meal'] },
  { name: 'Smoothie Cup', category: 'food-drink', tags: ['drink', 'healthy', 'blend'] },
  { name: 'Lemonade Jar', category: 'food-drink', tags: ['drink', 'citrus', 'refreshing'] },
  { name: 'Soup Ladle', category: 'food-drink', tags: ['cook', 'hot', 'bowl'] },
  { name: 'Cheese Wheel', category: 'food-drink', tags: ['dairy', 'french', 'slice'] },
  { name: 'Bread Loaf', category: 'food-drink', tags: ['bakery', 'wheat', 'toast'] },
  { name: 'Shrimp Prawn', category: 'food-drink', tags: ['seafood', 'grill', 'protein'] },
  { name: 'Mango Fruit', category: 'food-drink', tags: ['tropical', 'sweet', 'summer'] },
  { name: 'Waffle Stack', category: 'food-drink', tags: ['breakfast', 'sweet', 'syrup'] },
  { name: 'Burrito Wrap', category: 'food-drink', tags: ['mexican', 'wrap', 'lunch'] },
  { name: 'Energy Drink', category: 'food-drink', tags: ['can', 'boost', 'caffeine'] },

  // ─── Health Extended (20 icons) ───
  { name: 'Yoga Pose', category: 'health', tags: ['exercise', 'mindfulness', 'stretch'] },
  { name: 'Meditation Mind', category: 'health', tags: ['calm', 'zen', 'focus'] },
  { name: 'Running Shoes', category: 'health', tags: ['fitness', 'exercise', 'sport'] },
  { name: 'Weight Scale', category: 'health', tags: ['bmi', 'fitness', 'measure'] },
  { name: 'Heart Rate Graph', category: 'health', tags: ['ecg', 'cardiac', 'monitor'] },
  { name: 'Vitamin Capsule', category: 'health', tags: ['supplement', 'nutrition', 'health'] },
  { name: 'Blood Type', category: 'health', tags: ['blood', 'type', 'medical'] },
  { name: 'Kidney Organ', category: 'health', tags: ['organ', 'body', 'medical'] },
  { name: 'Sleep Rest', category: 'health', tags: ['rest', 'recovery', 'night'] },
  { name: 'Water Intake', category: 'health', tags: ['hydration', 'drink', 'daily'] },
  { name: 'Calorie Tracker', category: 'health', tags: ['nutrition', 'diet', 'food'] },
  { name: 'Mental Health', category: 'health', tags: ['wellness', 'emotion', 'support'] },
  { name: 'Bone X-ray', category: 'health', tags: ['skeleton', 'scan', 'fracture'] },
  { name: 'Blood Pressure', category: 'health', tags: ['pressure', 'bp', 'monitor'] },
  { name: 'Allergy Alert', category: 'health', tags: ['allergen', 'warning', 'reaction'] },
  { name: 'Vaccine Vial', category: 'health', tags: ['immunization', 'protection', 'dose'] },
  { name: 'Pharmacy Cross', category: 'health', tags: ['drugstore', 'medicine', 'rx'] },
  { name: 'Surgical Mask', category: 'health', tags: ['protection', 'respiratory', 'safety'] },
  { name: 'Pulse Oximeter', category: 'health', tags: ['oxygen', 'spo2', 'monitor'] },
  { name: 'Physical Therapy', category: 'health', tags: ['rehab', 'exercise', 'recovery'] },

  // ─── Education Extended (20 icons) ───
  { name: 'E-Learning Screen', category: 'education', tags: ['online', 'course', 'digital'] },
  { name: 'Quiz Question', category: 'education', tags: ['test', 'quiz', 'answer'] },
  { name: 'Certificate Badge', category: 'education', tags: ['diploma', 'award', 'degree'] },
  { name: 'Library Shelf', category: 'education', tags: ['books', 'collection', 'knowledge'] },
  { name: 'Flashcard Stack', category: 'education', tags: ['study', 'memory', 'review'] },
  { name: 'Science Flask', category: 'education', tags: ['chemistry', 'experiment', 'lab'] },
  { name: 'Math Formula', category: 'education', tags: ['equation', 'algebra', 'solve'] },
  { name: 'Language Letter', category: 'education', tags: ['alphabet', 'write', 'learn'] },
  { name: 'History Book', category: 'education', tags: ['past', 'events', 'timeline'] },
  { name: 'Geography Map', category: 'education', tags: ['countries', 'regions', 'world'] },
  { name: 'Music Clef', category: 'education', tags: ['notation', 'treble', 'music'] },
  { name: 'Art Canvas', category: 'education', tags: ['painting', 'create', 'express'] },
  { name: 'Programming Code', category: 'education', tags: ['coding', 'learn', 'tech'] },
  { name: 'Study Timer', category: 'education', tags: ['focus', 'pomodoro', 'time'] },
  { name: 'Whiteboard Marker', category: 'education', tags: ['teach', 'draw', 'explain'] },
  { name: 'Student ID Card', category: 'education', tags: ['identity', 'student', 'campus'] },
  { name: 'Exam Paper', category: 'education', tags: ['test', 'grade', 'sheet'] },
  { name: 'Debate Podium', category: 'education', tags: ['speak', 'argue', 'present'] },
  { name: 'Field Trip Bus', category: 'education', tags: ['school', 'trip', 'learn'] },
  { name: 'Science Rocket', category: 'education', tags: ['stem', 'build', 'launch'] },

  // ─── Travel Extended (20 icons) ───
  { name: 'Helicopter', category: 'travel', tags: ['aircraft', 'fly', 'rescue'] },
  { name: 'Scooter Motor', category: 'travel', tags: ['moped', 'city', 'ride'] },
  { name: 'Kayak Paddle', category: 'travel', tags: ['water', 'canoe', 'sport'] },
  { name: 'Cable Car', category: 'travel', tags: ['mountain', 'gondola', 'lift'] },
  { name: 'Ferry Boat', category: 'travel', tags: ['water', 'crossing', 'transport'] },
  { name: 'Tram Rail', category: 'travel', tags: ['city', 'transit', 'electric'] },
  { name: 'Subway Metro', category: 'travel', tags: ['underground', 'city', 'rapid'] },
  { name: 'Airport Gate', category: 'travel', tags: ['terminal', 'departure', 'boarding'] },
  { name: 'Hotel Key', category: 'travel', tags: ['room', 'checkin', 'stay'] },
  { name: 'Travel Insurance', category: 'travel', tags: ['coverage', 'protection', 'trip'] },
  { name: 'Currency Exchange', category: 'travel', tags: ['money', 'forex', 'travel'] },
  { name: 'Visa Stamp', category: 'travel', tags: ['permit', 'entry', 'border'] },
  { name: 'Tour Guide', category: 'travel', tags: ['explore', 'guide', 'visit'] },
  { name: 'Camera Selfie Stick', category: 'travel', tags: ['photo', 'tourist', 'selfie'] },
  { name: 'Backpacker Hike', category: 'travel', tags: ['trek', 'hike', 'explore'] },
  { name: 'Beach Resort', category: 'travel', tags: ['vacation', 'relax', 'tropical'] },
  { name: 'Mountain Lodge', category: 'travel', tags: ['cabin', 'retreat', 'nature'] },
  { name: 'Road Trip Map', category: 'travel', tags: ['drive', 'route', 'adventure'] },
  { name: 'River Cruise', category: 'travel', tags: ['water', 'tour', 'scenic'] },
  { name: 'Safari Jeep', category: 'travel', tags: ['wildlife', 'africa', 'explore'] },

  // ─── Entertainment Extended (20 icons) ───
  { name: 'Streaming Service', category: 'entertainment', tags: ['video', 'watch', 'online'] },
  { name: 'Live Concert', category: 'entertainment', tags: ['music', 'event', 'stage'] },
  { name: 'Arcade Machine', category: 'entertainment', tags: ['retro', 'gaming', 'coins'] },
  { name: 'Comic Book', category: 'entertainment', tags: ['manga', 'superhero', 'art'] },
  { name: 'Board Game Pawn', category: 'entertainment', tags: ['strategy', 'play', 'family'] },
  { name: 'Trophy Gaming', category: 'entertainment', tags: ['esports', 'achievement', 'win'] },
  { name: 'VR Gaming', category: 'entertainment', tags: ['virtual', 'immersive', 'headset'] },
  { name: 'Fireworks Display', category: 'entertainment', tags: ['celebration', 'sparkle', 'show'] },
  { name: 'Carnival Ride', category: 'entertainment', tags: ['fair', 'fun', 'thrill'] },
  { name: 'Escape Room', category: 'entertainment', tags: ['puzzle', 'adventure', 'solve'] },
  { name: 'Karaoke Mic', category: 'entertainment', tags: ['sing', 'fun', 'social'] },
  { name: 'Slot Machine', category: 'entertainment', tags: ['casino', 'luck', 'gamble'] },
  { name: 'Bowling Ball', category: 'entertainment', tags: ['sport', 'lane', 'pins'] },
  { name: 'Billiard Cue', category: 'entertainment', tags: ['pool', 'snooker', 'sport'] },
  { name: 'Dartboard', category: 'entertainment', tags: ['aim', 'target', 'pub'] },
  { name: 'Mini Golf', category: 'entertainment', tags: ['putt', 'fun', 'leisure'] },
  { name: 'Circus Tent', category: 'entertainment', tags: ['show', 'performance', 'fun'] },
  { name: 'Puppet Show', category: 'entertainment', tags: ['theater', 'story', 'children'] },
  { name: 'Fortune Cookie', category: 'entertainment', tags: ['luck', 'prediction', 'fun'] },
  { name: 'Neon Sign', category: 'entertainment', tags: ['night', 'glow', 'bar'] },

  // ─── Arrows & Navigation Extended (10 icons) ───
  { name: 'Diagonal Arrow', category: 'arrows-navigation', tags: ['angle', 'direction', 'link'] },
  { name: 'Circle Back', category: 'arrows-navigation', tags: ['undo', 'return', 'revert'] },
  { name: 'Swap Arrows', category: 'arrows-navigation', tags: ['exchange', 'switch', 'transfer'] },
  { name: 'Branch Fork', category: 'arrows-navigation', tags: ['split', 'diverge', 'route'] },
  { name: 'Merge Join', category: 'arrows-navigation', tags: ['combine', 'unite', 'flow'] },
  { name: 'Scroll Up Top', category: 'arrows-navigation', tags: ['top', 'jump', 'fast'] },
  { name: 'Keyboard Shortcut', category: 'arrows-navigation', tags: ['hotkey', 'cmd', 'quick'] },
  { name: 'Drag Handle', category: 'arrows-navigation', tags: ['reorder', 'move', 'grip'] },
  { name: 'Zoom In', category: 'arrows-navigation', tags: ['magnify', 'detail', 'enlarge'] },
  { name: 'Zoom Out', category: 'arrows-navigation', tags: ['shrink', 'overview', 'reduce'] },

  // ─── Security Extended (13 icons) ───
  { name: 'Two Factor Auth', category: 'security', tags: ['2fa', 'verify', 'login'] },
  { name: 'Fingerprint Scan', category: 'security', tags: ['biometric', 'identity', 'auth'] },
  { name: 'Face ID', category: 'security', tags: ['biometric', 'recognition', 'unlock'] },
  { name: 'Encrypted File', category: 'security', tags: ['cipher', 'secure', 'protect'] },
  { name: 'VPN Shield', category: 'security', tags: ['tunnel', 'private', 'network'] },
  { name: 'Password Manager', category: 'security', tags: ['vault', 'credentials', 'safe'] },
  { name: 'Phishing Hook', category: 'security', tags: ['scam', 'fraud', 'attack'] },
  { name: 'Malware Virus', category: 'security', tags: ['threat', 'infection', 'hack'] },
  { name: 'Security Audit', category: 'security', tags: ['scan', 'check', 'compliance'] },
  { name: 'Access Badge', category: 'security', tags: ['id', 'entry', 'permission'] },
  { name: 'Data Breach', category: 'security', tags: ['leak', 'exposure', 'incident'] },
  { name: 'Safe Vault', category: 'security', tags: ['bank', 'store', 'lock'] },
  { name: 'Token Code', category: 'security', tags: ['otp', 'auth', 'temporary'] },

  // ─── Files & Documents Extended (13 icons) ───
  { name: 'Spreadsheet Grid', category: 'files-documents', tags: ['excel', 'table', 'data'] },
  { name: 'Presentation Slides', category: 'files-documents', tags: ['pptx', 'deck', 'slide'] },
  { name: 'File CSV', category: 'files-documents', tags: ['data', 'comma', 'export'] },
  { name: 'File JSON', category: 'files-documents', tags: ['data', 'api', 'format'] },
  { name: 'File Video', category: 'files-documents', tags: ['mp4', 'movie', 'clip'] },
  { name: 'File Audio', category: 'files-documents', tags: ['mp3', 'sound', 'music'] },
  { name: 'File Archive', category: 'files-documents', tags: ['tar', 'rar', 'compress'] },
  { name: 'Folder Shared', category: 'files-documents', tags: ['share', 'team', 'access'] },
  { name: 'Cloud Sync', category: 'files-documents', tags: ['sync', 'backup', 'update'] },
  { name: 'Version Control', category: 'files-documents', tags: ['history', 'commit', 'diff'] },
  { name: 'Document Template', category: 'files-documents', tags: ['blank', 'form', 'start'] },
  { name: 'Print Preview', category: 'files-documents', tags: ['layout', 'paper', 'print'] },
  { name: 'File Rename', category: 'files-documents', tags: ['edit', 'name', 'change'] },

  // ─── Social Media Extended (15 icons) ───
  { name: 'Story Circle', category: 'social-media', tags: ['stories', 'post', 'ephemeral'] },
  { name: 'Reels Video', category: 'social-media', tags: ['short', 'video', 'viral'] },
  { name: 'Comment Thread', category: 'social-media', tags: ['reply', 'discuss', 'opinion'] },
  { name: 'Influencer Badge', category: 'social-media', tags: ['creator', 'brand', 'sponsor'] },
  { name: 'Profile Avatar', category: 'social-media', tags: ['account', 'photo', 'user'] },
  { name: 'Follower Count', category: 'social-media', tags: ['audience', 'subscribers', 'reach'] },
  { name: 'Trending Arrow', category: 'social-media', tags: ['hot', 'viral', 'popular'] },
  { name: 'Direct Message', category: 'social-media', tags: ['dm', 'private', 'chat'] },
  { name: 'Bio Link', category: 'social-media', tags: ['profile', 'url', 'link'] },
  { name: 'Engagement Rate', category: 'social-media', tags: ['interact', 'metric', 'reach'] },
  { name: 'Content Schedule', category: 'social-media', tags: ['post', 'plan', 'calendar'] },
  { name: 'Social Analytics', category: 'social-media', tags: ['stats', 'growth', 'data'] },
  { name: 'Community Group', category: 'social-media', tags: ['members', 'forum', 'network'] },
  { name: 'Creator Studio', category: 'social-media', tags: ['create', 'content', 'tools'] },
  { name: 'Collab Request', category: 'social-media', tags: ['partner', 'invite', 'work'] },

  // ─── Design Tools Extended (15 icons) ───
  { name: 'Vector Path', category: 'design-tools', tags: ['bezier', 'curve', 'node'] },
  { name: 'Color Swatch', category: 'design-tools', tags: ['palette', 'theme', 'brand'] },
  { name: 'Gradient Fill', category: 'design-tools', tags: ['blend', 'color', 'transition'] },
  { name: 'Shadow Drop', category: 'design-tools', tags: ['depth', 'effect', 'layer'] },
  { name: 'Artboard Frame', category: 'design-tools', tags: ['canvas', 'workspace', 'frame'] },
  { name: 'Component Block', category: 'design-tools', tags: ['reuse', 'ui', 'library'] },
  { name: 'Wireframe Layout', category: 'design-tools', tags: ['mockup', 'ux', 'prototype'] },
  { name: 'Pixel Perfect', category: 'design-tools', tags: ['precise', 'align', 'sharp'] },
  { name: 'Export Asset', category: 'design-tools', tags: ['output', 'save', 'format'] },
  { name: 'Prototype Link', category: 'design-tools', tags: ['interaction', 'flow', 'ux'] },
  { name: 'Accessibility Check', category: 'design-tools', tags: ['wcag', 'contrast', 'a11y'] },
  { name: 'Grid Columns', category: 'design-tools', tags: ['layout', 'responsive', 'css'] },
  { name: 'Spacing Gutter', category: 'design-tools', tags: ['margin', 'padding', 'space'] },
  { name: 'Icon Set', category: 'design-tools', tags: ['icons', 'library', 'system'] },
  { name: 'Brand Identity', category: 'design-tools', tags: ['logo', 'mark', 'visual'] },

  // ─── Home & Lifestyle (40 icons) ───
  { name: 'Armchair', category: 'home-lifestyle', tags: ['furniture', 'sit', 'relax'] },
  { name: 'Sofa Couch', category: 'home-lifestyle', tags: ['furniture', 'lounge', 'living'] },
  { name: 'Bed Bedroom', category: 'home-lifestyle', tags: ['sleep', 'rest', 'room'] },
  { name: 'Bathtub', category: 'home-lifestyle', tags: ['bath', 'relax', 'wash'] },
  { name: 'Refrigerator', category: 'home-lifestyle', tags: ['kitchen', 'cool', 'food'] },
  { name: 'Microwave Oven', category: 'home-lifestyle', tags: ['kitchen', 'heat', 'cook'] },
  { name: 'Table Lamp', category: 'home-lifestyle', tags: ['light', 'decor', 'room'] },
  { name: 'Smart TV', category: 'home-lifestyle', tags: ['screen', 'entertainment', 'room'] },
  { name: 'House Plant', category: 'home-lifestyle', tags: ['indoor', 'green', 'decor'] },
  { name: 'Picture Frame', category: 'home-lifestyle', tags: ['photo', 'wall', 'decor'] },
  { name: 'Candle Flame', category: 'home-lifestyle', tags: ['light', 'cozy', 'aroma'] },
  { name: 'Pillow Cushion', category: 'home-lifestyle', tags: ['comfort', 'sleep', 'decor'] },
  { name: 'Blanket Throw', category: 'home-lifestyle', tags: ['warm', 'cozy', 'comfort'] },
  { name: 'Curtain Window', category: 'home-lifestyle', tags: ['window', 'decor', 'privacy'] },
  { name: 'Doorbell', category: 'home-lifestyle', tags: ['entry', 'ring', 'visitor'] },
  { name: 'Washing Machine', category: 'home-lifestyle', tags: ['laundry', 'clean', 'clothes'] },
  { name: 'Iron Clothes', category: 'home-lifestyle', tags: ['press', 'laundry', 'flat'] },
  { name: 'Vacuum Cleaner', category: 'home-lifestyle', tags: ['clean', 'floor', 'dust'] },
  { name: 'Broom Sweep', category: 'home-lifestyle', tags: ['clean', 'floor', 'dust'] },
  { name: 'Tool Wrench', category: 'home-lifestyle', tags: ['fix', 'repair', 'maintain'] },
  { name: 'Paint Roller', category: 'home-lifestyle', tags: ['paint', 'wall', 'decor'] },
  { name: 'Garden Hose', category: 'home-lifestyle', tags: ['water', 'garden', 'outdoor'] },
  { name: 'Shovel Spade', category: 'home-lifestyle', tags: ['dig', 'garden', 'soil'] },
  { name: 'Lawn Mower', category: 'home-lifestyle', tags: ['grass', 'garden', 'cut'] },
  { name: 'Barbecue Grill', category: 'home-lifestyle', tags: ['outdoor', 'cook', 'grill'] },
  { name: 'Patio Furniture', category: 'home-lifestyle', tags: ['outdoor', 'chair', 'table'] },
  { name: 'Swimming Pool', category: 'home-lifestyle', tags: ['swim', 'water', 'yard'] },
  { name: 'Security Camera', category: 'home-lifestyle', tags: ['surveillance', 'protect', 'watch'] },
  { name: 'Smart Lock', category: 'home-lifestyle', tags: ['door', 'digital', 'access'] },
  { name: 'Thermostat', category: 'home-lifestyle', tags: ['temperature', 'hvac', 'climate'] },
  { name: 'Solar Panel', category: 'home-lifestyle', tags: ['energy', 'green', 'power'] },
  { name: 'Home Office Desk', category: 'home-lifestyle', tags: ['remote', 'work', 'setup'] },
  { name: 'Bookshelf', category: 'home-lifestyle', tags: ['books', 'storage', 'decor'] },
  { name: 'Kitchen Knife', category: 'home-lifestyle', tags: ['cook', 'cut', 'chef'] },
  { name: 'Cutting Board', category: 'home-lifestyle', tags: ['cook', 'prep', 'kitchen'] },
  { name: 'Wine Rack', category: 'home-lifestyle', tags: ['storage', 'wine', 'cellar'] },
  { name: 'Spice Rack', category: 'home-lifestyle', tags: ['kitchen', 'cook', 'flavor'] },
  { name: 'Meal Prep Container', category: 'home-lifestyle', tags: ['food', 'store', 'healthy'] },
  { name: 'Recycle Bin', category: 'home-lifestyle', tags: ['eco', 'waste', 'green'] },
  { name: 'Home Energy', category: 'home-lifestyle', tags: ['utility', 'bill', 'save'] },

  // ─── Sports (35 icons) ───
  { name: 'Soccer Ball', category: 'sports', tags: ['football', 'game', 'team'] },
  { name: 'Basketball Hoop', category: 'sports', tags: ['nba', 'court', 'score'] },
  { name: 'Tennis Racket', category: 'sports', tags: ['court', 'serve', 'match'] },
  { name: 'Baseball Bat', category: 'sports', tags: ['hit', 'pitch', 'diamond'] },
  { name: 'Golf Club', category: 'sports', tags: ['putt', 'drive', 'birdie'] },
  { name: 'American Football', category: 'sports', tags: ['nfl', 'touchdown', 'field'] },
  { name: 'Rugby Ball', category: 'sports', tags: ['tackle', 'try', 'scrum'] },
  { name: 'Volleyball Net', category: 'sports', tags: ['serve', 'spike', 'team'] },
  { name: 'Swimming Goggles', category: 'sports', tags: ['swim', 'pool', 'lap'] },
  { name: 'Cycling Helmet', category: 'sports', tags: ['bike', 'protect', 'road'] },
  { name: 'Running Track', category: 'sports', tags: ['sprint', 'marathon', 'race'] },
  { name: 'Weightlifting Bar', category: 'sports', tags: ['gym', 'lift', 'strength'] },
  { name: 'Boxing Gloves', category: 'sports', tags: ['punch', 'fight', 'ring'] },
  { name: 'Ski Slope', category: 'sports', tags: ['winter', 'downhill', 'snow'] },
  { name: 'Snowboard', category: 'sports', tags: ['winter', 'trick', 'slope'] },
  { name: 'Surfboard Wave', category: 'sports', tags: ['surf', 'ocean', 'ride'] },
  { name: 'Skateboard', category: 'sports', tags: ['skate', 'trick', 'urban'] },
  { name: 'Archery Target', category: 'sports', tags: ['bow', 'arrow', 'aim'] },
  { name: 'Fencing Sword', category: 'sports', tags: ['duel', 'blade', 'sport'] },
  { name: 'Gymnastics Ring', category: 'sports', tags: ['olympic', 'strength', 'aerial'] },
  { name: 'Table Tennis Paddle', category: 'sports', tags: ['ping-pong', 'table', 'ball'] },
  { name: 'Badminton Shuttle', category: 'sports', tags: ['birdie', 'racket', 'net'] },
  { name: 'Ice Skate Boot', category: 'sports', tags: ['ice', 'rink', 'winter'] },
  { name: 'Hockey Stick', category: 'sports', tags: ['ice', 'puck', 'goal'] },
  { name: 'Cricket Bat', category: 'sports', tags: ['wicket', 'pitch', 'bowl'] },
  { name: 'Polo Mallet', category: 'sports', tags: ['horse', 'stick', 'field'] },
  { name: 'Javelin Throw', category: 'sports', tags: ['olympic', 'track', 'field'] },
  { name: 'Discus Throw', category: 'sports', tags: ['olympic', 'circular', 'field'] },
  { name: 'Hurdles Jump', category: 'sports', tags: ['track', 'leap', 'sprint'] },
  { name: 'Medal Podium', category: 'sports', tags: ['award', 'first', 'winner'] },
  { name: 'Sports Whistle', category: 'sports', tags: ['referee', 'signal', 'game'] },
  { name: 'Stopwatch Timer', category: 'sports', tags: ['time', 'record', 'race'] },
  { name: 'Team Jersey', category: 'sports', tags: ['uniform', 'club', 'player'] },
  { name: 'Fitness Band', category: 'sports', tags: ['wearable', 'track', 'health'] },
  { name: 'Jump Rope', category: 'sports', tags: ['cardio', 'skip', 'exercise'] },

  // ─── Animals (30 icons) ───
  { name: 'Dog Paw', category: 'animals', tags: ['pet', 'dog', 'cute'] },
  { name: 'Cat Face', category: 'animals', tags: ['pet', 'cat', 'feline'] },
  { name: 'Bird Perch', category: 'animals', tags: ['feather', 'tweet', 'fly'] },
  { name: 'Fish Tank', category: 'animals', tags: ['aquarium', 'swim', 'pet'] },
  { name: 'Rabbit Bunny', category: 'animals', tags: ['hop', 'cute', 'pet'] },
  { name: 'Horse Gallop', category: 'animals', tags: ['equine', 'ride', 'farm'] },
  { name: 'Cow Dairy', category: 'animals', tags: ['farm', 'milk', 'cattle'] },
  { name: 'Pig Farm', category: 'animals', tags: ['farm', 'oink', 'animal'] },
  { name: 'Sheep Wool', category: 'animals', tags: ['flock', 'farm', 'soft'] },
  { name: 'Chicken Hen', category: 'animals', tags: ['farm', 'egg', 'poultry'] },
  { name: 'Duck Swim', category: 'animals', tags: ['water', 'quack', 'bird'] },
  { name: 'Elephant Trunk', category: 'animals', tags: ['safari', 'large', 'grey'] },
  { name: 'Lion Mane', category: 'animals', tags: ['king', 'safari', 'roar'] },
  { name: 'Tiger Stripes', category: 'animals', tags: ['wild', 'stripe', 'fierce'] },
  { name: 'Bear Grizzly', category: 'animals', tags: ['wild', 'forest', 'large'] },
  { name: 'Wolf Howl', category: 'animals', tags: ['wild', 'pack', 'moon'] },
  { name: 'Fox Tail', category: 'animals', tags: ['clever', 'forest', 'red'] },
  { name: 'Deer Antler', category: 'animals', tags: ['forest', 'gentle', 'antler'] },
  { name: 'Turtle Shell', category: 'animals', tags: ['slow', 'protect', 'ocean'] },
  { name: 'Snake Coil', category: 'animals', tags: ['reptile', 'slither', 'venom'] },
  { name: 'Frog Leap', category: 'animals', tags: ['amphibian', 'jump', 'pond'] },
  { name: 'Butterfly Wings', category: 'animals', tags: ['insect', 'transform', 'color'] },
  { name: 'Bee Honeycomb', category: 'animals', tags: ['honey', 'sting', 'pollinate'] },
  { name: 'Spider Web', category: 'animals', tags: ['arachnid', 'web', 'catch'] },
  { name: 'Penguin Waddle', category: 'animals', tags: ['arctic', 'bird', 'cute'] },
  { name: 'Panda Bear', category: 'animals', tags: ['bamboo', 'cute', 'china'] },
  { name: 'Octopus Tentacle', category: 'animals', tags: ['ocean', 'ink', 'arms'] },
  { name: 'Whale Tail', category: 'animals', tags: ['ocean', 'large', 'mammal'] },
  { name: 'Eagle Flight', category: 'animals', tags: ['bird', 'predator', 'soar'] },
  { name: 'Chameleon Color', category: 'animals', tags: ['reptile', 'adapt', 'blend'] },

  // ─── Shopping (30 icons) ───
  { name: 'Shopping Cart', category: 'shopping', tags: ['cart', 'buy', 'checkout'] },
  { name: 'Shopping Bag', category: 'shopping', tags: ['retail', 'purchase', 'store'] },
  { name: 'Price Tag Label', category: 'shopping', tags: ['cost', 'discount', 'sale'] },
  { name: 'Barcode Scanner', category: 'shopping', tags: ['scan', 'product', 'code'] },
  { name: 'Gift Box', category: 'shopping', tags: ['present', 'wrap', 'occasion'] },
  { name: 'Store Front', category: 'shopping', tags: ['shop', 'retail', 'browse'] },
  { name: 'Delivery Truck', category: 'shopping', tags: ['ship', 'logistics', 'arrive'] },
  { name: 'Package Box', category: 'shopping', tags: ['parcel', 'shipped', 'receive'] },
  { name: 'Return Arrow', category: 'shopping', tags: ['refund', 'exchange', 'back'] },
  { name: 'Wishlist Heart', category: 'shopping', tags: ['favorite', 'save', 'want'] },
  { name: 'Coupon Code', category: 'shopping', tags: ['discount', 'promo', 'save'] },
  { name: 'Sale Percent', category: 'shopping', tags: ['off', 'deal', 'reduce'] },
  { name: 'Product Review', category: 'shopping', tags: ['rating', 'star', 'feedback'] },
  { name: 'Online Store', category: 'shopping', tags: ['ecommerce', 'website', 'buy'] },
  { name: 'Payment Terminal', category: 'shopping', tags: ['pos', 'swipe', 'checkout'] },
  { name: 'Loyalty Points', category: 'shopping', tags: ['reward', 'earn', 'redeem'] },
  { name: 'Order Track', category: 'shopping', tags: ['status', 'track', 'update'] },
  { name: 'Seller Merchant', category: 'shopping', tags: ['vendor', 'store', 'sell'] },
  { name: 'Clothing Rack', category: 'shopping', tags: ['fashion', 'apparel', 'wear'] },
  { name: 'Size Guide', category: 'shopping', tags: ['fit', 'measure', 'chart'] },
  { name: 'Flash Sale', category: 'shopping', tags: ['limited', 'quick', 'deal'] },
  { name: 'Bundle Deal', category: 'shopping', tags: ['combo', 'save', 'package'] },
  { name: 'Subscription Box', category: 'shopping', tags: ['recurring', 'monthly', 'curated'] },
  { name: 'Digital Receipt', category: 'shopping', tags: ['bill', 'email', 'payment'] },
  { name: 'Inventory Stock', category: 'shopping', tags: ['warehouse', 'count', 'manage'] },
  { name: 'Checkout Counter', category: 'shopping', tags: ['register', 'pay', 'finish'] },
  { name: 'Product Catalog', category: 'shopping', tags: ['browse', 'category', 'list'] },
  { name: 'Membership Card', category: 'shopping', tags: ['vip', 'member', 'access'] },
  { name: 'Cash Register', category: 'shopping', tags: ['till', 'pay', 'receipt'] },
  { name: 'Drop Shipping', category: 'shopping', tags: ['supplier', 'ship', 'ecommerce'] },

  // ─── Weather (20 icons) ───
  { name: 'Sunny Day', category: 'weather', tags: ['clear', 'bright', 'warm'] },
  { name: 'Partly Cloudy', category: 'weather', tags: ['overcast', 'mixed', 'mild'] },
  { name: 'Rainy Day', category: 'weather', tags: ['rain', 'wet', 'umbrella'] },
  { name: 'Snow Storm', category: 'weather', tags: ['blizzard', 'cold', 'white'] },
  { name: 'Thunderstorm', category: 'weather', tags: ['lightning', 'thunder', 'heavy'] },
  { name: 'Foggy Morning', category: 'weather', tags: ['fog', 'haze', 'visibility'] },
  { name: 'Windy Breeze', category: 'weather', tags: ['wind', 'gust', 'breezy'] },
  { name: 'Hail Storm', category: 'weather', tags: ['ice', 'pellets', 'storm'] },
  { name: 'Drizzle Light', category: 'weather', tags: ['light', 'mist', 'sprinkle'] },
  { name: 'Sunny Cloudy Mix', category: 'weather', tags: ['partly', 'sun', 'cloud'] },
  { name: 'Night Clear', category: 'weather', tags: ['stars', 'moon', 'cool'] },
  { name: 'Night Cloudy', category: 'weather', tags: ['overcast', 'dark', 'night'] },
  { name: 'Temperature High', category: 'weather', tags: ['hot', 'heat', 'summer'] },
  { name: 'Temperature Low', category: 'weather', tags: ['cold', 'freeze', 'winter'] },
  { name: 'UV Index', category: 'weather', tags: ['sun', 'radiation', 'protect'] },
  { name: 'Humidity Level', category: 'weather', tags: ['moisture', 'damp', 'sticky'] },
  { name: 'Wind Speed', category: 'weather', tags: ['mph', 'gust', 'direction'] },
  { name: 'Visibility Range', category: 'weather', tags: ['clear', 'see', 'distance'] },
  { name: 'Weather Alert', category: 'weather', tags: ['warning', 'severe', 'emergency'] },
  { name: 'Sunrise Forecast', category: 'weather', tags: ['morning', 'dawn', 'early'] },

  // ─── Maps & Navigation (20 icons) ───
  { name: 'City Map', category: 'maps', tags: ['urban', 'streets', 'navigate'] },
  { name: 'GPS Location', category: 'maps', tags: ['pin', 'coordinates', 'find'] },
  { name: 'Route Planner', category: 'maps', tags: ['directions', 'path', 'trip'] },
  { name: 'Street View', category: 'maps', tags: ['panorama', 'explore', '360'] },
  { name: 'Turn Right', category: 'maps', tags: ['direction', 'navigate', 'road'] },
  { name: 'Turn Left', category: 'maps', tags: ['direction', 'navigate', 'road'] },
  { name: 'U-Turn', category: 'maps', tags: ['reverse', 'back', 'direction'] },
  { name: 'Toll Road', category: 'maps', tags: ['highway', 'pay', 'drive'] },
  { name: 'Traffic Light', category: 'maps', tags: ['signal', 'stop', 'go'] },
  { name: 'Parking Sign', category: 'maps', tags: ['park', 'lot', 'car'] },
  { name: 'Rest Area', category: 'maps', tags: ['stop', 'break', 'highway'] },
  { name: 'Gas Station', category: 'maps', tags: ['fuel', 'fill', 'refuel'] },
  { name: 'Hospital Nearby', category: 'maps', tags: ['emergency', 'near', 'medical'] },
  { name: 'Restaurant Pin', category: 'maps', tags: ['food', 'eat', 'nearby'] },
  { name: 'Hotel Marker', category: 'maps', tags: ['stay', 'accommodation', 'near'] },
  { name: 'ATM Location', category: 'maps', tags: ['bank', 'cash', 'nearby'] },
  { name: 'Airport Pin', category: 'maps', tags: ['terminal', 'fly', 'location'] },
  { name: 'Beach Marker', category: 'maps', tags: ['coast', 'summer', 'visit'] },
  { name: 'Park Location', category: 'maps', tags: ['green', 'outdoor', 'recreation'] },
  { name: 'Shopping Center', category: 'maps', tags: ['mall', 'retail', 'near'] },

  // ─── Gaming (30 icons) ───
  { name: 'Game Controller Classic', category: 'gaming', tags: ['console', 'play', 'buttons'] },
  { name: 'Game Joystick', category: 'gaming', tags: ['arcade', 'stick', 'control'] },
  { name: 'Gaming Headset', category: 'gaming', tags: ['voice', 'audio', 'team'] },
  { name: 'Game Achievement', category: 'gaming', tags: ['unlock', 'badge', 'reward'] },
  { name: 'Leaderboard Rank', category: 'gaming', tags: ['score', 'top', 'compete'] },
  { name: 'Character Avatar', category: 'gaming', tags: ['player', 'persona', 'rpg'] },
  { name: 'Inventory Bag', category: 'gaming', tags: ['items', 'loot', 'collect'] },
  { name: 'Health Bar', category: 'gaming', tags: ['hp', 'life', 'status'] },
  { name: 'Mana Bar', category: 'gaming', tags: ['magic', 'energy', 'spell'] },
  { name: 'Experience Points', category: 'gaming', tags: ['xp', 'level', 'progress'] },
  { name: 'Game Map', category: 'gaming', tags: ['world', 'explore', 'quest'] },
  { name: 'Sword Weapon', category: 'gaming', tags: ['fight', 'attack', 'rpg'] },
  { name: 'Shield Defense', category: 'gaming', tags: ['protect', 'block', 'armor'] },
  { name: 'Potion Bottle', category: 'gaming', tags: ['heal', 'buff', 'drink'] },
  { name: 'Treasure Chest', category: 'gaming', tags: ['loot', 'gold', 'reward'] },
  { name: 'Dungeon Key', category: 'gaming', tags: ['unlock', 'door', 'secret'] },
  { name: 'Spawn Point', category: 'gaming', tags: ['respawn', 'start', 'location'] },
  { name: 'Game Timer Clock', category: 'gaming', tags: ['countdown', 'race', 'limit'] },
  { name: 'Multiplayer Network', category: 'gaming', tags: ['online', 'co-op', 'connect'] },
  { name: 'Esports Trophy', category: 'gaming', tags: ['competition', 'win', 'champion'] },
  { name: 'Game Settings', category: 'gaming', tags: ['config', 'options', 'difficulty'] },
  { name: 'Pause Screen', category: 'gaming', tags: ['stop', 'menu', 'break'] },
  { name: 'Game Over Screen', category: 'gaming', tags: ['die', 'retry', 'end'] },
  { name: 'Loading Screen', category: 'gaming', tags: ['wait', 'progress', 'connect'] },
  { name: 'Pixel Character', category: 'gaming', tags: ['retro', '8-bit', 'sprite'] },
  { name: 'Dungeon Room', category: 'gaming', tags: ['level', 'explore', 'encounter'] },
  { name: 'Boss Fight', category: 'gaming', tags: ['challenge', 'enemy', 'battle'] },
  { name: 'Speedrun Timer', category: 'gaming', tags: ['fast', 'record', 'compete'] },
  { name: 'Clan Tag', category: 'gaming', tags: ['group', 'team', 'guild'] },
  { name: 'Emote Gesture', category: 'gaming', tags: ['expression', 'react', 'dance'] },

  // ─── Finance (25 icons) ───
  { name: 'Bank Note', category: 'finance', tags: ['cash', 'money', 'bill'] },
  { name: 'Piggy Bank', category: 'finance', tags: ['save', 'savings', 'money'] },
  { name: 'Bank Vault', category: 'finance', tags: ['secure', 'safe', 'bank'] },
  { name: 'Bitcoin Crypto', category: 'finance', tags: ['btc', 'digital', 'currency'] },
  { name: 'Euro Sign', category: 'finance', tags: ['eur', 'europe', 'currency'] },
  { name: 'Stock Market', category: 'finance', tags: ['trade', 'invest', 'equity'] },
  { name: 'Investment Fund', category: 'finance', tags: ['portfolio', 'return', 'grow'] },
  { name: 'Tax Document', category: 'finance', tags: ['irs', 'return', 'deduction'] },
  { name: 'Budget Planner', category: 'finance', tags: ['plan', 'expense', 'income'] },
  { name: 'Expense Tracker', category: 'finance', tags: ['spend', 'log', 'track'] },
  { name: 'Income Arrow Up', category: 'finance', tags: ['earn', 'profit', 'gain'] },
  { name: 'Loss Arrow Down', category: 'finance', tags: ['loss', 'decrease', 'red'] },
  { name: 'Loan Application', category: 'finance', tags: ['borrow', 'debt', 'bank'] },
  { name: 'Mortgage Home', category: 'finance', tags: ['house', 'loan', 'property'] },
  { name: 'Insurance Policy', category: 'finance', tags: ['cover', 'protect', 'plan'] },
  { name: 'Dividend Yield', category: 'finance', tags: ['return', 'income', 'stock'] },
  { name: 'Bond Certificate', category: 'finance', tags: ['fixed', 'income', 'secure'] },
  { name: 'Mutual Fund', category: 'finance', tags: ['pool', 'diversify', 'invest'] },
  { name: 'Exchange Rate', category: 'finance', tags: ['forex', 'currency', 'convert'] },
  { name: 'Net Worth', category: 'finance', tags: ['assets', 'value', 'total'] },
  { name: 'Debt Reduction', category: 'finance', tags: ['payoff', 'free', 'clear'] },
  { name: 'Financial Plan', category: 'finance', tags: ['goal', 'strategy', 'future'] },
  { name: 'Payroll Check', category: 'finance', tags: ['salary', 'wage', 'pay'] },
  { name: 'Wire Transfer', category: 'finance', tags: ['send', 'bank', 'transaction'] },
  { name: 'Compound Interest', category: 'finance', tags: ['grow', 'time', 'return'] },

  // ─── Science (20 icons) ───
  { name: 'Science Beaker', category: 'science', tags: ['chemistry', 'lab', 'experiment'] },
  { name: 'Atom Structure', category: 'science', tags: ['physics', 'nucleus', 'electron'] },
  { name: 'Molecule Bond', category: 'science', tags: ['chemistry', 'compound', 'element'] },
  { name: 'DNA Strand', category: 'science', tags: ['genetics', 'biology', 'gene'] },
  { name: 'Microscope Lab', category: 'science', tags: ['magnify', 'examine', 'biology'] },
  { name: 'Telescope Observe', category: 'science', tags: ['stars', 'space', 'astronomy'] },
  { name: 'Magnet Force', category: 'science', tags: ['attract', 'repel', 'field'] },
  { name: 'Battery Cell', category: 'science', tags: ['energy', 'charge', 'store'] },
  { name: 'Solar System', category: 'science', tags: ['planets', 'orbit', 'space'] },
  { name: 'Gravity Pull', category: 'science', tags: ['force', 'attract', 'physics'] },
  { name: 'Light Spectrum', category: 'science', tags: ['color', 'prism', 'wave'] },
  { name: 'Sound Wave', category: 'science', tags: ['audio', 'frequency', 'vibration'] },
  { name: 'Electric Circuit', category: 'science', tags: ['current', 'voltage', 'resistance'] },
  { name: 'Chemical Formula', category: 'science', tags: ['equation', 'symbol', 'element'] },
  { name: 'Ecosystem Chart', category: 'science', tags: ['nature', 'biology', 'food-web'] },
  { name: 'Climate Graph', category: 'science', tags: ['temperature', 'change', 'data'] },
  { name: 'Radiation Symbol', category: 'science', tags: ['nuclear', 'hazard', 'warning'] },
  { name: 'Petri Dish', category: 'science', tags: ['culture', 'bacteria', 'lab'] },
  { name: 'Centrifuge Spin', category: 'science', tags: ['separate', 'lab', 'rotate'] },
  { name: 'Gene Sequence', category: 'science', tags: ['dna', 'genome', 'code'] },
];

