/**
 * Maps each Icon Forge definition to a Lucide icon filename (without `.svg`).
 * Lucide icons live at: node_modules/lucide-static/icons/<name>.svg
 *
 * Only platform-default icons (style: 'line-art') use this mapping.
 * AI generation (other styles) is invoked at runtime per user.
 */
export const LUCIDE_MAPPING: Record<string, string> = {
  // Technology
  Laptop: 'laptop',
  Smartphone: 'smartphone',
  'Desktop Monitor': 'monitor',
  'Server Rack': 'server',
  'Wi-Fi Signal': 'wifi',
  Bluetooth: 'bluetooth',
  'USB Drive': 'usb',
  Microchip: 'cpu',
  'Robot Head': 'bot',
  'Code Brackets': 'brackets',
  'Terminal Window': 'terminal',
  'Database Cylinder': 'database',
  'Cloud Upload': 'cloud-upload',
  'Cloud Download': 'cloud-download',
  Keyboard: 'keyboard',
  'Mouse Cursor': 'mouse-pointer-2',
  Printer: 'printer',
  Webcam: 'webcam',
  Smartwatch: 'watch',
  'VR Headset': 'glasses',
  Drone: 'drone',
  'Satellite Dish': 'satellite-dish',
  'Battery Charging': 'battery-charging',
  'QR Code': 'qr-code',
  'Hard Drive': 'hard-drive',
  'Ethernet Cable': 'ethernet-port',
  'Power Button': 'power',
  'Settings Gear': 'settings',
  'CPU Fan': 'fan',
  'SSD Drive': 'hard-drive-download',

  // Business
  Briefcase: 'briefcase',
  'Line Chart Rising': 'trending-up',
  'Bar Chart': 'chart-bar',
  'Pie Chart': 'chart-pie',
  'Dollar Sign': 'dollar-sign',
  'Credit Card': 'credit-card',
  Wallet: 'wallet',
  Handshake: 'handshake',
  'Presentation Board': 'presentation',
  'Target Bullseye': 'target',
  'Trophy Cup': 'trophy',
  'Calendar Schedule': 'calendar-days',
  'Clock Timer': 'clock',
  'Clipboard Checklist': 'clipboard-list',
  'Invoice Receipt': 'receipt',
  'Office Building': 'building-2',
  'Lightbulb Idea': 'lightbulb',
  'Rocket Launch': 'rocket',
  Megaphone: 'megaphone',
  'Funnel Pipeline': 'funnel',
  'Badge Certificate': 'badge-check',
  'Coins Stack': 'coins',
  'Diamond Gem': 'gem',
  'Stamp Seal': 'stamp',
  Hourglass: 'hourglass',

  // Communication
  'Chat Bubble': 'message-circle',
  'Chat Bubbles Double': 'messages-square',
  'Email Envelope': 'mail',
  'Phone Ringing': 'phone-call',
  'Video Call': 'video',
  'Notification Bell': 'bell',
  'Send Paper Plane': 'send',
  'Inbox Tray': 'inbox',
  'At Symbol': 'at-sign',
  'Link Chain': 'link',
  'Share Network': 'share-2',
  'Antenna Broadcast': 'antenna',
  'Contact Book': 'contact',
  'Emoji Smile': 'smile',
  'Emoji Sad': 'frown',
  'Thumbs Up': 'thumbs-up',
  'Thumbs Down': 'thumbs-down',
  'Quote Marks': 'quote',
  'Microphone Voice': 'mic',
  'Translate Globe': 'languages',

  // Nature
  Sun: 'sun',
  'Moon Crescent': 'moon',
  'Star Five Point': 'star',
  Cloud: 'cloud',
  'Rain Drops': 'cloud-rain',
  'Lightning Bolt': 'zap',
  Snowflake: 'snowflake',
  Rainbow: 'rainbow',
  'Tree Oak': 'tree-deciduous',
  'Pine Tree': 'tree-pine',
  Leaf: 'leaf',
  'Flower Rose': 'rose',
  Cactus: 'sprout',
  'Mountain Peak': 'mountain',
  'Ocean Wave': 'waves',
  'Flame Fire': 'flame',
  'Water Droplet': 'droplet',
  'Wind Breeze': 'wind',
  Volcano: 'mountain-snow',
  'Globe Earth': 'globe',
  'Sunrise Horizon': 'sunrise',
  Mushroom: 'sprout',
  Seashell: 'shell',
  Tornado: 'tornado',
  'Coral Reef': 'fish',

  // Food & Drink
  'Coffee Cup': 'coffee',
  'Pizza Slice': 'pizza',
  Hamburger: 'hamburger',
  'Ice Cream Cone': 'ice-cream-cone',
  'Birthday Cake': 'cake',
  'Wine Glass': 'wine',
  'Beer Mug': 'beer',
  'Apple Fruit': 'apple',
  'Cooking Pot': 'cooking-pot',
  'Fork and Knife': 'utensils',
  'Sushi Roll': 'fish',
  Taco: 'sandwich',
  Cupcake: 'cake-slice',
  'Hot Dog': 'sandwich',
  Donut: 'donut',
  'Cocktail Glass': 'martini',
  'Tea Cup': 'coffee',
  'Popcorn Box': 'popcorn',
  Avocado: 'apple',
  'Egg Fried': 'egg-fried',

  // Health
  'Heart Pulse': 'heart-pulse',
  Stethoscope: 'stethoscope',
  'Pill Capsule': 'pill',
  'Syringe Needle': 'syringe',
  'First Aid Kit': 'briefcase-medical',
  'Hospital Cross': 'cross',
  'DNA Helix': 'dna',
  Brain: 'brain',
  Tooth: 'bone',
  'Eye Vision': 'eye',
  Lungs: 'wind',
  Bandage: 'bandage',
  Thermometer: 'thermometer',
  Wheelchair: 'accessibility',
  Ambulance: 'ambulance',

  // Education
  'Open Book': 'book-open',
  'Closed Book': 'book',
  'Graduation Cap': 'graduation-cap',
  'Pencil Writing': 'pencil',
  'School Backpack': 'backpack',
  'Globe Stand': 'globe',
  Microscope: 'microscope',
  Telescope: 'telescope',
  Calculator: 'calculator',
  'Test Tube': 'test-tube',
  'Atom Model': 'atom',
  Chalkboard: 'presentation',
  'Notebook Spiral': 'notebook',
  'Ruler Straight': 'ruler',
  'Paint Palette': 'palette',

  // Travel
  Airplane: 'plane',
  'Car Sedan': 'car',
  'Train Locomotive': 'train-front',
  'Ship Boat': 'sailboat',
  Bicycle: 'bike',
  Bus: 'bus',
  'Taxi Cab': 'car-taxi-front',
  'Compass Direction': 'compass',
  'Map Pin': 'map-pin',
  'Luggage Suitcase': 'luggage',
  Passport: 'book-marked',
  'Tent Camping': 'tent',
  'Beach Umbrella': 'umbrella',
  Lighthouse: 'tower-control',
  'Hot Air Balloon': 'balloon',

  // Entertainment
  'Music Note': 'music',
  Headphones: 'headphones',
  'Guitar Acoustic': 'guitar',
  'Microphone Stand': 'mic-vocal',
  'Film Camera': 'film',
  'Photo Camera': 'camera',
  'Game Controller': 'gamepad-2',
  'Dice Pair': 'dices',
  'Playing Card': 'spade',
  'Puzzle Piece': 'puzzle',
  'Theater Masks': 'theater',
  'Paint Brush Art': 'paintbrush',
  'Video Play Button': 'circle-play',
  'Ticket Stub': 'ticket',
  'Magic Wand': 'wand-sparkles',
  'Crown Royal': 'crown',
  'Piano Keys': 'piano',
  Drum: 'drum',
  Clapperboard: 'clapperboard',
  'Vinyl Record': 'disc-album',

  // Arrows & Navigation
  'Arrow Right': 'arrow-right',
  'Arrow Left': 'arrow-left',
  'Arrow Up': 'arrow-up',
  'Arrow Down': 'arrow-down',
  'Refresh Arrows': 'refresh-cw',
  'Expand Fullscreen': 'maximize',
  'Compress Minimize': 'minimize',
  'Menu Hamburger': 'menu',
  'Grid View': 'grid-2x2',
  'List View': 'list',
  'Search Magnifier': 'search',
  'Filter Funnel': 'filter',
  'Sort Lines': 'arrow-down-narrow-wide',
  'Home House': 'house',
  'Cross Close': 'x',

  // Security
  'Lock Closed': 'lock',
  'Lock Open': 'lock-open',
  Key: 'key',
  'Shield Check': 'shield-check',
  'Shield Warning': 'shield-alert',
  'Eye Visible': 'eye',
  'Eye Hidden': 'eye-off',
  'Alarm Siren': 'siren',
  'CCTV Camera': 'cctv',
  'Bug Insect': 'bug',
  'Firewall Brick': 'shield',
  'Incognito Hat': 'venetian-mask',

  // Files & Documents
  'File Document': 'file-text',
  'File PDF': 'file',
  'File Image': 'file-image',
  'File Code': 'file-code',
  'Folder Closed': 'folder',
  'Folder Open': 'folder-open',
  'Zip Archive': 'archive',
  'Trash Can': 'trash-2',
  'Download Arrow': 'download',
  'Upload Arrow': 'upload',
  'Copy Duplicate': 'copy',
  'Floppy Save': 'save',

  // Social Media
  'Heart Like': 'heart',
  'Bookmark Flag': 'bookmark',
  'User Profile': 'user-round',
  'Users Group': 'users-round',
  Hashtag: 'hash',
  'Camera Selfie': 'camera',
  'Live Dot': 'circle-dot',
  'Follow Plus': 'user-plus',
  'Verified Check': 'verified',
  'Share Curved Arrow': 'share',

  // Design Tools
  'Color Palette': 'palette',
  'Pen Tool': 'pen-tool',
  'Crop Frame': 'crop',
  'Layers Stack': 'layers',
  Eyedropper: 'pipette',
  'Grid Layout': 'grid-3x3',
  'Typography A': 'type',
  'Ruler Measure': 'ruler-dimension-line',
  Eraser: 'eraser',
  'Shapes Circle': 'circle',

  // Technology Extended
  'Cloud Storage': 'cloud',
  'API Endpoint': 'plug',
  'Git Branch': 'git-branch',
  'Docker Container': 'container',
  'Package Module': 'package',
  'Bug Report': 'bug',
  'Pull Request': 'git-pull-request',
  'Code Fork': 'git-fork',
  'Monitor Dashboard': 'layout-dashboard',
  'Network Graph': 'network',
  Firewall: 'shield',
  'Load Balancer': 'server',
  'Memory RAM': 'memory-stick',
  'GPU Card': 'circuit-board',
  'IoT Sensor': 'radio-tower',
  'AR Glasses': 'glasses',
  'NFC Tag': 'nfc',
  Touchscreen: 'tablet-smartphone',
  'Projector Screen': 'projector',
  'Raspberry Pi': 'cpu',

  // Business Extended
  'Org Chart': 'network',
  'Kanban Board': 'kanban',
  'Email Campaign': 'mail-check',
  'Customer Support': 'headset',
  'Analytics Report': 'chart-column',
  'Survey Form': 'clipboard',
  'Workflow Arrow': 'workflow',
  'Team Meeting': 'users',
  'Growth Trend': 'trending-up',
  'Risk Warning': 'triangle-alert',
  'Contract Document': 'file-signature',
  'Partnership Puzzle': 'puzzle',
  'Budget Forecast': 'chart-no-axes-column',
  'Subscription Plan': 'badge-dollar-sign',
  'Milestone Flag': 'milestone',

  // Communication Extended
  'Voice Message': 'mic',
  'Group Chat': 'message-square-dot',
  'Read Receipt': 'check-check',
  'Reply Arrow': 'reply',
  'Forward Message': 'forward',
  'Mute Bell': 'bell-off',
  'Live Stream': 'tv-minimal-play',
  'Podcast Wave': 'podcast',
  'Feedback Star': 'star',
  'Broadcast Tower': 'tower-broadcast',
  'Chat Bot': 'bot',
  'News Feed': 'newspaper',
  'Mention Tag': 'at-sign',
  'Pin Message': 'pin',
  'Emoji Reaction': 'smile-plus',

  // Nature Extended
  'Bamboo Stalk': 'leaf',
  'Cherry Blossom': 'flower-2',
  Sunflower: 'flower',
  'Palm Tree': 'palm-tree',
  'Fern Plant': 'plant-2',
  'Acorn Nut': 'nut',
  'Frost Ice': 'snowflake',
  'Fog Mist': 'cloud-fog',
  Hailstorm: 'cloud-hail',
  'Drizzle Rain': 'cloud-drizzle',
  'Sand Dune': 'mountain',
  'Cliff Edge': 'mountain-snow',
  Waterfall: 'waves',
  'Hot Spring': 'flame',
  'Comet Meteor': 'star-shooting',
  'Northern Lights': 'sparkles',
  'Eclipse Solar': 'sun',
  'Pebble Stone': 'circle',
  'Crystal Gem': 'gem',
  'Feather Quill': 'feather',

  // Food & Drink Extended
  'Ramen Bowl': 'bowl-steam',
  'Steak Meat': 'beef',
  'Salad Bowl': 'salad',
  Croissant: 'croissant',
  'Bento Box': 'box',
  'Smoothie Cup': 'cup-soda',
  'Lemonade Jar': 'glass-water',
  'Soup Ladle': 'soup',
  'Cheese Wheel': 'cheese',
  'Bread Loaf': 'bread-slice',
  'Shrimp Prawn': 'fish',
  'Mango Fruit': 'citrus',
  'Waffle Stack': 'sandwich',
  'Burrito Wrap': 'wrap',
  'Energy Drink': 'battery',

  // Health Extended
  'Yoga Pose': 'person-standing',
  'Meditation Mind': 'brain',
  'Running Shoes': 'footprints',
  'Weight Scale': 'scale',
  'Heart Rate Graph': 'activity',
  'Vitamin Capsule': 'pill',
  'Blood Type': 'droplets',
  'Kidney Organ': 'heart',
  'Sleep Rest': 'bed',
  'Water Intake': 'glass-water',
  'Calorie Tracker': 'flame',
  'Mental Health': 'brain',
  'Bone X-ray': 'bone',
  'Blood Pressure': 'gauge',
  'Allergy Alert': 'triangle-alert',
  'Vaccine Vial': 'syringe',
  'Pharmacy Cross': 'cross',
  'Surgical Mask': 'shield',
  'Pulse Oximeter': 'heart-pulse',
  'Physical Therapy': 'dumbbell',

  // Education Extended
  'E-Learning Screen': 'monitor-play',
  'Quiz Question': 'circle-help',
  'Certificate Badge': 'award',
  'Library Shelf': 'library',
  'Flashcard Stack': 'layers',
  'Science Flask': 'flask-conical',
  'Math Formula': 'sigma',
  'Language Letter': 'a-large-small',
  'History Book': 'book-marked',
  'Geography Map': 'map',
  'Music Clef': 'music',
  'Art Canvas': 'palette',
  'Programming Code': 'code-2',
  'Study Timer': 'timer',
  'Whiteboard Marker': 'marker',
  'Student ID Card': 'id-card',
  'Exam Paper': 'file-text',
  'Debate Podium': 'presentation',
  'Field Trip Bus': 'bus',
  'Science Rocket': 'rocket',

  // Travel Extended
  Helicopter: 'plane',
  'Scooter Motor': 'bike',
  'Kayak Paddle': 'sailboat',
  'Cable Car': 'cable-car',
  'Ferry Boat': 'ship',
  'Tram Rail': 'tram-front',
  'Subway Metro': 'train-subway',
  'Airport Gate': 'door-open',
  'Hotel Key': 'hotel',
  'Travel Insurance': 'shield-check',
  'Currency Exchange': 'arrow-left-right',
  'Visa Stamp': 'stamp',
  'Tour Guide': 'map-pin',
  'Camera Selfie Stick': 'camera',
  'Backpacker Hike': 'backpack',
  'Beach Resort': 'umbrella',
  'Mountain Lodge': 'tent',
  'Road Trip Map': 'map',
  'River Cruise': 'sailboat',
  'Safari Jeep': 'car',

  // Entertainment Extended
  'Streaming Service': 'tv-minimal',
  'Live Concert': 'music-4',
  'Arcade Machine': 'gamepad',
  'Comic Book': 'book-image',
  'Board Game Pawn': 'chess',
  'Trophy Gaming': 'trophy',
  'VR Gaming': 'glasses',
  'Fireworks Display': 'sparkles',
  'Carnival Ride': 'ferris-wheel',
  'Escape Room': 'lock',
  'Karaoke Mic': 'mic-vocal',
  'Slot Machine': 'dices',
  'Bowling Ball': 'circle-dot',
  'Billiard Cue': 'zap',
  Dartboard: 'target',
  'Mini Golf': 'circle',
  'Circus Tent': 'tent',
  'Puppet Show': 'hand',
  'Fortune Cookie': 'cookie',
  'Neon Sign': 'zap',

  // Arrows & Navigation Extended
  'Diagonal Arrow': 'arrow-up-right',
  'Circle Back': 'rotate-ccw',
  'Swap Arrows': 'arrow-left-right',
  'Branch Fork': 'git-fork',
  'Merge Join': 'merge',
  'Scroll Up Top': 'arrow-up-to-line',
  'Keyboard Shortcut': 'keyboard',
  'Drag Handle': 'grip-vertical',
  'Zoom In': 'zoom-in',
  'Zoom Out': 'zoom-out',

  // Security Extended
  'Two Factor Auth': 'shield-ellipsis',
  'Fingerprint Scan': 'fingerprint',
  'Face ID': 'scan-face',
  'Encrypted File': 'file-lock-2',
  'VPN Shield': 'shield-half',
  'Password Manager': 'vault',
  'Phishing Hook': 'fish-hook',
  'Malware Virus': 'virus',
  'Security Audit': 'scan-eye',
  'Access Badge': 'badge',
  'Data Breach': 'shield-x',
  'Safe Vault': 'vault',
  'Token Code': 'hash',

  // Files & Documents Extended
  'Spreadsheet Grid': 'table-2',
  'Presentation Slides': 'presentation',
  'File CSV': 'file-spreadsheet',
  'File JSON': 'file-json',
  'File Video': 'file-video',
  'File Audio': 'file-audio',
  'File Archive': 'file-archive',
  'Folder Shared': 'folder-open',
  'Cloud Sync': 'cloud-cog',
  'Version Control': 'git-commit-horizontal',
  'Document Template': 'file-plus',
  'Print Preview': 'printer',
  'File Rename': 'file-pen',

  // Social Media Extended
  'Story Circle': 'circle-user',
  'Reels Video': 'clapperboard',
  'Comment Thread': 'message-circle',
  'Influencer Badge': 'badge-check',
  'Profile Avatar': 'user-round',
  'Follower Count': 'users',
  'Trending Arrow': 'trending-up',
  'Direct Message': 'send',
  'Bio Link': 'link',
  'Engagement Rate': 'bar-chart',
  'Content Schedule': 'calendar-check',
  'Social Analytics': 'chart-line',
  'Community Group': 'users-round',
  'Creator Studio': 'video',
  'Collab Request': 'handshake',

  // Design Tools Extended
  'Vector Path': 'spline',
  'Color Swatch': 'swatch-book',
  'Gradient Fill': 'blend',
  'Shadow Drop': 'shadow',
  'Artboard Frame': 'frame',
  'Component Block': 'component',
  'Wireframe Layout': 'layout-template',
  'Pixel Perfect': 'scan',
  'Export Asset': 'package-open',
  'Prototype Link': 'link-2',
  'Accessibility Check': 'accessibility',
  'Grid Columns': 'columns-3',
  'Spacing Gutter': 'separator-horizontal',
  'Icon Set': 'shapes',
  'Brand Identity': 'badge',

  // Home & Lifestyle
  Armchair: 'armchair',
  'Sofa Couch': 'sofa',
  'Bed Bedroom': 'bed',
  Bathtub: 'bath',
  Refrigerator: 'refrigerator',
  'Microwave Oven': 'microwave',
  'Table Lamp': 'lamp',
  'Smart TV': 'tv',
  'House Plant': 'flower-2',
  'Picture Frame': 'frame',
  'Candle Flame': 'flame',
  'Pillow Cushion': 'pillow',
  'Blanket Throw': 'blanket',
  'Curtain Window': 'aperture',
  Doorbell: 'bell-ring',
  'Washing Machine': 'washing-machine',
  'Iron Clothes': 'shirt',
  'Vacuum Cleaner': 'zap',
  'Broom Sweep': 'broom',
  'Tool Wrench': 'wrench',
  'Paint Roller': 'paint-roller',
  'Garden Hose': 'waves',
  'Shovel Spade': 'shovel',
  'Lawn Mower': 'tree-deciduous',
  'Barbecue Grill': 'flame',
  'Patio Furniture': 'armchair',
  'Swimming Pool': 'waves',
  'Security Camera': 'cctv',
  'Smart Lock': 'lock',
  Thermostat: 'thermometer',
  'Solar Panel': 'sun',
  'Home Office Desk': 'monitor',
  Bookshelf: 'library',
  'Kitchen Knife': 'knife',
  'Cutting Board': 'square',
  'Wine Rack': 'wine',
  'Spice Rack': 'leaf',
  'Meal Prep Container': 'box',
  'Recycle Bin': 'recycle',
  'Home Energy': 'zap',

  // Sports
  'Soccer Ball': 'circle-dot',
  'Basketball Hoop': 'circle',
  'Tennis Racket': 'circle-dashed',
  'Baseball Bat': 'minus',
  'Golf Club': 'flag',
  'American Football': 'circle',
  'Rugby Ball': 'circle',
  'Volleyball Net': 'minus',
  'Swimming Goggles': 'glasses',
  'Cycling Helmet': 'bike',
  'Running Track': 'footprints',
  'Weightlifting Bar': 'dumbbell',
  'Boxing Gloves': 'hand',
  'Ski Slope': 'mountain-snow',
  Snowboard: 'snowflake',
  'Surfboard Wave': 'waves',
  Skateboard: 'square',
  'Archery Target': 'target',
  'Fencing Sword': 'sword',
  'Gymnastics Ring': 'circle',
  'Table Tennis Paddle': 'circle-dot',
  'Badminton Shuttle': 'bird',
  'Ice Skate Boot': 'snowflake',
  'Hockey Stick': 'minus',
  'Cricket Bat': 'minus',
  'Polo Mallet': 'horse',
  'Javelin Throw': 'arrow-up',
  'Discus Throw': 'circle',
  'Hurdles Jump': 'arrow-up',
  'Medal Podium': 'medal',
  'Sports Whistle': 'wind',
  'Stopwatch Timer': 'timer',
  'Team Jersey': 'shirt',
  'Fitness Band': 'watch',
  'Jump Rope': 'minus',

  // Animals
  'Dog Paw': 'dog',
  'Cat Face': 'cat',
  'Bird Perch': 'bird',
  'Fish Tank': 'fish',
  'Rabbit Bunny': 'rabbit',
  'Horse Gallop': 'horse',
  'Cow Dairy': 'cow',
  'Pig Farm': 'pig',
  'Sheep Wool': 'squirrel',
  'Chicken Hen': 'bird',
  'Duck Swim': 'bird',
  'Elephant Trunk': 'elephant',
  'Lion Mane': 'cat',
  'Tiger Stripes': 'cat',
  'Bear Grizzly': 'bear',
  'Wolf Howl': 'dog',
  'Fox Tail': 'squirrel',
  'Deer Antler': 'deer',
  'Turtle Shell': 'turtle',
  'Snake Coil': 'snake',
  'Frog Leap': 'frog',
  'Butterfly Wings': 'butterfly',
  'Bee Honeycomb': 'bee',
  'Spider Web': 'spider',
  'Penguin Waddle': 'bird',
  'Panda Bear': 'panda',
  'Octopus Tentacle': 'fish',
  'Whale Tail': 'fish',
  'Eagle Flight': 'bird',
  'Chameleon Color': 'squirrel',

  // Shopping
  'Shopping Cart': 'shopping-cart',
  'Shopping Bag': 'shopping-bag',
  'Price Tag Label': 'tag',
  'Barcode Scanner': 'barcode',
  'Gift Box': 'gift',
  'Store Front': 'store',
  'Delivery Truck': 'truck',
  'Package Box': 'package',
  'Return Arrow': 'package-check',
  'Wishlist Heart': 'heart',
  'Coupon Code': 'ticket',
  'Sale Percent': 'percent',
  'Product Review': 'star',
  'Online Store': 'store',
  'Payment Terminal': 'credit-card',
  'Loyalty Points': 'gem',
  'Order Track': 'map-pin',
  'Seller Merchant': 'user-check',
  'Clothing Rack': 'shirt',
  'Size Guide': 'ruler',
  'Flash Sale': 'zap',
  'Bundle Deal': 'package-plus',
  'Subscription Box': 'box',
  'Digital Receipt': 'receipt',
  'Inventory Stock': 'clipboard-list',
  'Checkout Counter': 'shopping-cart',
  'Product Catalog': 'layout-grid',
  'Membership Card': 'credit-card',
  'Cash Register': 'landmark',
  'Drop Shipping': 'truck',

  // Weather
  'Sunny Day': 'sun',
  'Partly Cloudy': 'cloud-sun',
  'Rainy Day': 'cloud-rain',
  'Snow Storm': 'cloud-snow',
  Thunderstorm: 'cloud-lightning',
  'Foggy Morning': 'cloud-fog',
  'Windy Breeze': 'wind',
  'Hail Storm': 'cloud-hail',
  'Drizzle Light': 'cloud-drizzle',
  'Sunny Cloudy Mix': 'cloud-sun',
  'Night Clear': 'moon',
  'Night Cloudy': 'cloud-moon',
  'Temperature High': 'thermometer-sun',
  'Temperature Low': 'thermometer-snowflake',
  'UV Index': 'sun',
  'Humidity Level': 'droplets',
  'Wind Speed': 'wind',
  'Visibility Range': 'eye',
  'Weather Alert': 'triangle-alert',
  'Sunrise Forecast': 'sunrise',

  // Maps
  'City Map': 'map',
  'GPS Location': 'navigation',
  'Route Planner': 'route',
  'Street View': 'street-view',
  'Turn Right': 'corner-right-up',
  'Turn Left': 'corner-left-up',
  'U-Turn': 'rotate-cw',
  'Toll Road': 'road',
  'Traffic Light': 'traffic-cone',
  'Parking Sign': 'parking-circle',
  'Rest Area': 'coffee',
  'Gas Station': 'fuel',
  'Hospital Nearby': 'hospital',
  'Restaurant Pin': 'utensils',
  'Hotel Marker': 'hotel',
  'ATM Location': 'landmark',
  'Airport Pin': 'plane-landing',
  'Beach Marker': 'umbrella',
  'Park Location': 'trees',
  'Shopping Center': 'store',

  // Gaming
  'Game Controller Classic': 'gamepad-2',
  'Game Joystick': 'joystick',
  'Gaming Headset': 'headset',
  'Game Achievement': 'award',
  'Leaderboard Rank': 'list-ordered',
  'Character Avatar': 'user-round',
  'Inventory Bag': 'backpack',
  'Health Bar': 'heart',
  'Mana Bar': 'zap',
  'Experience Points': 'star',
  'Game Map': 'map',
  'Sword Weapon': 'sword',
  'Shield Defense': 'shield',
  'Potion Bottle': 'flask-round',
  'Treasure Chest': 'chest',
  'Dungeon Key': 'key-round',
  'Spawn Point': 'map-pin',
  'Game Timer Clock': 'timer',
  'Multiplayer Network': 'network',
  'Esports Trophy': 'trophy',
  'Game Settings': 'settings',
  'Pause Screen': 'pause-circle',
  'Game Over Screen': 'x-circle',
  'Loading Screen': 'loader-circle',
  'Pixel Character': 'square',
  'Dungeon Room': 'door-closed',
  'Boss Fight': 'sword',
  'Speedrun Timer': 'zap',
  'Clan Tag': 'users',
  'Emote Gesture': 'smile',

  // Finance
  'Bank Note': 'banknote',
  'Piggy Bank': 'piggy-bank',
  'Bank Vault': 'vault',
  'Bitcoin Crypto': 'bitcoin',
  'Euro Sign': 'euro',
  'Stock Market': 'trending-up',
  'Investment Fund': 'chart-pie',
  'Tax Document': 'file-text',
  'Budget Planner': 'calculator',
  'Expense Tracker': 'receipt',
  'Income Arrow Up': 'trending-up',
  'Loss Arrow Down': 'trending-down',
  'Loan Application': 'landmark',
  'Mortgage Home': 'house',
  'Insurance Policy': 'shield-check',
  'Dividend Yield': 'percent',
  'Bond Certificate': 'file-badge',
  'Mutual Fund': 'pie-chart',
  'Exchange Rate': 'arrow-left-right',
  'Net Worth': 'wallet',
  'Debt Reduction': 'minus-circle',
  'Financial Plan': 'chart-line',
  'Payroll Check': 'banknote',
  'Wire Transfer': 'send',
  'Compound Interest': 'trending-up',

  // Science
  'Science Beaker': 'beaker',
  'Atom Structure': 'atom',
  'Molecule Bond': 'circle-dot',
  'DNA Strand': 'dna',
  'Microscope Lab': 'microscope',
  'Telescope Observe': 'telescope',
  'Magnet Force': 'magnet',
  'Battery Cell': 'battery',
  'Solar System': 'orbit',
  'Gravity Pull': 'arrow-down-to-dot',
  'Light Spectrum': 'rainbow',
  'Sound Wave': 'audio-waveform',
  'Electric Circuit': 'zap',
  'Chemical Formula': 'flask-conical',
  'Ecosystem Chart': 'network',
  'Climate Graph': 'chart-line',
  'Radiation Symbol': 'radiation',
  'Petri Dish': 'circle',
  'Centrifuge Spin': 'rotate-cw',
  'Gene Sequence': 'dna',
};
