/**
 * Maps each Icon Forge definition to a Lucide icon filename (without `.svg`).
 * Lucide icons live at: node_modules/lucide-static/icons/<name>.svg
 *
 * Only platform-default icons (style: 'line-art') use this mapping.
 * AI generation (other styles) is invoked at runtime per user.
 */
export const LUCIDE_MAPPING: Record<string, string> = {
  // Technology
  Laptop: 'laptop',
  Smartphone: 'smartphone',
  'Desktop Monitor': 'monitor',
  'Server Rack': 'server',
  'Wi-Fi Signal': 'wifi',
  Bluetooth: 'bluetooth',
  'USB Drive': 'usb',
  Microchip: 'cpu',
  'Robot Head': 'bot',
  'Code Brackets': 'brackets',
  'Terminal Window': 'terminal',
  'Database Cylinder': 'database',
  'Cloud Upload': 'cloud-upload',
  'Cloud Download': 'cloud-download',
  Keyboard: 'keyboard',
  'Mouse Cursor': 'mouse-pointer-2',
  Printer: 'printer',
  Webcam: 'webcam',
  Smartwatch: 'watch',
  'VR Headset': 'glasses',
  Drone: 'drone',
  'Satellite Dish': 'satellite-dish',
  'Battery Charging': 'battery-charging',
  'QR Code': 'qr-code',
  'Hard Drive': 'hard-drive',
  'Ethernet Cable': 'ethernet-port',
  'Power Button': 'power',
  'Settings Gear': 'settings',
  'CPU Fan': 'fan',
  'SSD Drive': 'hard-drive-download',

  // Business
  Briefcase: 'briefcase',
  'Line Chart Rising': 'trending-up',
  'Bar Chart': 'chart-bar',
  'Pie Chart': 'chart-pie',
  'Dollar Sign': 'dollar-sign',
  'Credit Card': 'credit-card',
  Wallet: 'wallet',
  Handshake: 'handshake',
  'Presentation Board': 'presentation',
  'Target Bullseye': 'target',
  'Trophy Cup': 'trophy',
  'Calendar Schedule': 'calendar-days',
  'Clock Timer': 'clock',
  'Clipboard Checklist': 'clipboard-list',
  'Invoice Receipt': 'receipt',
  'Office Building': 'building-2',
  'Lightbulb Idea': 'lightbulb',
  'Rocket Launch': 'rocket',
  Megaphone: 'megaphone',
  'Funnel Pipeline': 'funnel',
  'Badge Certificate': 'badge-check',
  'Coins Stack': 'coins',
  'Diamond Gem': 'gem',
  'Stamp Seal': 'stamp',
  Hourglass: 'hourglass',

  // Communication
  'Chat Bubble': 'message-circle',
  'Chat Bubbles Double': 'messages-square',
  'Email Envelope': 'mail',
  'Phone Ringing': 'phone-call',
  'Video Call': 'video',
  'Notification Bell': 'bell',
  'Send Paper Plane': 'send',
  'Inbox Tray': 'inbox',
  'At Symbol': 'at-sign',
  'Link Chain': 'link',
  'Share Network': 'share-2',
  'Antenna Broadcast': 'antenna',
  'Contact Book': 'contact',
  'Emoji Smile': 'smile',
  'Emoji Sad': 'frown',
  'Thumbs Up': 'thumbs-up',
  'Thumbs Down': 'thumbs-down',
  'Quote Marks': 'quote',
  'Microphone Voice': 'mic',
  'Translate Globe': 'languages',

  // Nature
  Sun: 'sun',
  'Moon Crescent': 'moon',
  'Star Five Point': 'star',
  Cloud: 'cloud',
  'Rain Drops': 'cloud-rain',
  'Lightning Bolt': 'zap',
  Snowflake: 'snowflake',
  Rainbow: 'rainbow',
  'Tree Oak': 'tree-deciduous',
  'Pine Tree': 'tree-pine',
  Leaf: 'leaf',
  'Flower Rose': 'rose',
  Cactus: 'sprout',
  'Mountain Peak': 'mountain',
  'Ocean Wave': 'waves',
  'Flame Fire': 'flame',
  'Water Droplet': 'droplet',
  'Wind Breeze': 'wind',
  Volcano: 'mountain-snow',
  'Globe Earth': 'globe',
  'Sunrise Horizon': 'sunrise',
  Mushroom: 'sprout',
  Seashell: 'shell',
  Tornado: 'tornado',
  'Coral Reef': 'fish',

  // Food & Drink
  'Coffee Cup': 'coffee',
  'Pizza Slice': 'pizza',
  Hamburger: 'hamburger',
  'Ice Cream Cone': 'ice-cream-cone',
  'Birthday Cake': 'cake',
  'Wine Glass': 'wine',
  'Beer Mug': 'beer',
  'Apple Fruit': 'apple',
  'Cooking Pot': 'cooking-pot',
  'Fork and Knife': 'utensils',
  'Sushi Roll': 'fish',
  Taco: 'sandwich',
  Cupcake: 'cake-slice',
  'Hot Dog': 'sandwich',
  Donut: 'donut',
  'Cocktail Glass': 'martini',
  'Tea Cup': 'coffee',
  'Popcorn Box': 'popcorn',
  Avocado: 'apple',
  'Egg Fried': 'egg-fried',

  // Health
  'Heart Pulse': 'heart-pulse',
  Stethoscope: 'stethoscope',
  'Pill Capsule': 'pill',
  'Syringe Needle': 'syringe',
  'First Aid Kit': 'briefcase-medical',
  'Hospital Cross': 'cross',
  'DNA Helix': 'dna',
  Brain: 'brain',
  Tooth: 'bone',
  'Eye Vision': 'eye',
  Lungs: 'wind',
  Bandage: 'bandage',
  Thermometer: 'thermometer',
  Wheelchair: 'accessibility',
  Ambulance: 'ambulance',

  // Education
  'Open Book': 'book-open',
  'Closed Book': 'book',
  'Graduation Cap': 'graduation-cap',
  'Pencil Writing': 'pencil',
  'School Backpack': 'backpack',
  'Globe Stand': 'globe',
  Microscope: 'microscope',
  Telescope: 'telescope',
  Calculator: 'calculator',
  'Test Tube': 'test-tube',
  'Atom Model': 'atom',
  Chalkboard: 'presentation',
  'Notebook Spiral': 'notebook',
  'Ruler Straight': 'ruler',
  'Paint Palette': 'palette',

  // Travel
  Airplane: 'plane',
  'Car Sedan': 'car',
  'Train Locomotive': 'train-front',
  'Ship Boat': 'sailboat',
  Bicycle: 'bike',
  Bus: 'bus',
  'Taxi Cab': 'car-taxi-front',
  'Compass Direction': 'compass',
  'Map Pin': 'map-pin',
  'Luggage Suitcase': 'luggage',
  Passport: 'book-marked',
  'Tent Camping': 'tent',
  'Beach Umbrella': 'umbrella',
  Lighthouse: 'tower-control',
  'Hot Air Balloon': 'balloon',

  // Entertainment
  'Music Note': 'music',
  Headphones: 'headphones',
  'Guitar Acoustic': 'guitar',
  'Microphone Stand': 'mic-vocal',
  'Film Camera': 'film',
  'Photo Camera': 'camera',
  'Game Controller': 'gamepad-2',
  'Dice Pair': 'dices',
  'Playing Card': 'spade',
  'Puzzle Piece': 'puzzle',
  'Theater Masks': 'theater',
  'Paint Brush Art': 'paintbrush',
  'Video Play Button': 'circle-play',
  'Ticket Stub': 'ticket',
  'Magic Wand': 'wand-sparkles',
  'Crown Royal': 'crown',
  'Piano Keys': 'piano',
  Drum: 'drum',
  Clapperboard: 'clapperboard',
  'Vinyl Record': 'disc-album',

  // Arrows & Navigation
  'Arrow Right': 'arrow-right',
  'Arrow Left': 'arrow-left',
  'Arrow Up': 'arrow-up',
  'Arrow Down': 'arrow-down',
  'Refresh Arrows': 'refresh-cw',
  'Expand Fullscreen': 'maximize',
  'Compress Minimize': 'minimize',
  'Menu Hamburger': 'menu',
  'Grid View': 'grid-2x2',
  'List View': 'list',
  'Search Magnifier': 'search',
  'Filter Funnel': 'filter',
  'Sort Lines': 'arrow-down-narrow-wide',
  'Home House': 'house',
  'Cross Close': 'x',

  // Security
  'Lock Closed': 'lock',
  'Lock Open': 'lock-open',
  Key: 'key',
  'Shield Check': 'shield-check',
  'Shield Warning': 'shield-alert',
  'Eye Visible': 'eye',
  'Eye Hidden': 'eye-off',
  'Alarm Siren': 'siren',
  'CCTV Camera': 'cctv',
  'Bug Insect': 'bug',
  'Firewall Brick': 'shield',
  'Incognito Hat': 'venetian-mask',

  // Files & Documents
  'File Document': 'file-text',
  'File PDF': 'file',
  'File Image': 'file-image',
  'File Code': 'file-code',
  'Folder Closed': 'folder',
  'Folder Open': 'folder-open',
  'Zip Archive': 'archive',
  'Trash Can': 'trash-2',
  'Download Arrow': 'download',
  'Upload Arrow': 'upload',
  'Copy Duplicate': 'copy',
  'Floppy Save': 'save',

  // Social Media
  'Heart Like': 'heart',
  'Bookmark Flag': 'bookmark',
  'User Profile': 'user-round',
  'Users Group': 'users-round',
  Hashtag: 'hash',
  'Camera Selfie': 'camera',
  'Live Dot': 'circle-dot',
  'Follow Plus': 'user-plus',
  'Verified Check': 'verified',
  'Share Curved Arrow': 'share',

  // Design Tools
  'Color Palette': 'palette',
  'Pen Tool': 'pen-tool',
  'Crop Frame': 'crop',
  'Layers Stack': 'layers',
  Eyedropper: 'pipette',
  'Grid Layout': 'grid-3x3',
  'Typography A': 'type',
  'Ruler Measure': 'ruler-dimension-line',
  Eraser: 'eraser',
  'Shapes Circle': 'circle',
};
