/**
 * Per-framework package builders. Each builder turns a list of icons (DB rows)
 * into a directory tree of files that can be zipped and shipped to a user as
 * a locally-installable package for their language/framework of choice.
 *
 * v1: packages are NOT published anywhere — the user downloads the zip,
 * extracts it, then `npm install ./icon-forge-react` (or pubspec local path,
 * or SwiftPM local path, or Gradle includeBuild) into their project.
 */
import {
  FRAMEWORK_BY_ID,
  type Framework,
  type FrameworkId,
} from '@iconforge/shared';
import { kebabCase, pascalCase, snakeCase } from '@iconforge/shared';

/**
 * Frameworks where the npm `npm install <tarball-url>` flow works.
 * For others (Flutter / SwiftUI / Kotlin), users still need the zip + local
 * path install — those ecosystems consume Git URLs, not arbitrary tarballs.
 */
export const NPM_INSTALLABLE: ReadonlySet<FrameworkId> = new Set<FrameworkId>([
  'react',
  'nextjs',
  'vue',
  'svelte',
  'angular',
  'react-native',
]);

export type IconInput = {
  name: string;
  svg: string;
};

export type PackageFile = { path: string; content: string };

export type PackageOutput = {
  rootDir: string; // top-level folder name inside the zip
  files: PackageFile[]; // every file relative to rootDir/
  archiveName: string; // suggested .zip filename
};

const PACKAGE_VERSION = '0.1.0';
const PACKAGE_LICENSE = 'MIT';

function bannerComment(label: string, style: string): string {
  return `// Generated by Icon Forge. Style: ${style}. License: ${PACKAGE_LICENSE}.\n// ${label}\n`;
}

// ─── React ────────────────────────────────────────────────────────────────
function buildReact(icons: IconInput[], style: string, opts: { withUseClient: boolean; nameSuffix: string; pkgName: string; description: string }): PackageOutput {
  const rootDir = opts.pkgName;
  const files: PackageFile[] = [];
  const exports: string[] = [];

  for (const icon of icons) {
    const compName = pascalCase(icon.name) + 'Icon';
    const filename = `${compName}.tsx`;
    const useClient = opts.withUseClient ? `'use client';\n\n` : '';
    files.push({
      path: `src/${filename}`,
      content: bannerComment(filename, style) + useClient +
        FRAMEWORK_BY_ID.react.generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
    exports.push(`export { default as ${compName} } from './${compName}';`);
  }

  files.push({
    path: 'src/index.ts',
    content: bannerComment('index.ts', style) + exports.join('\n') + '\n',
  });

  files.push({
    path: 'package.json',
    content: JSON.stringify(
      {
        name: opts.pkgName,
        version: PACKAGE_VERSION,
        description: opts.description,
        license: PACKAGE_LICENSE,
        main: './src/index.ts',
        types: './src/index.ts',
        files: ['src'],
        sideEffects: false,
        peerDependencies: { react: '>=18' },
        keywords: ['icons', 'react', 'svg', 'icon-forge', style],
      },
      null,
      2,
    ) + '\n',
  });

  files.push({
    path: 'README.md',
    content: `# ${opts.pkgName}\n\n${opts.description}\n\n## Install (locally)\n\n\`\`\`bash\nnpm install ./${opts.pkgName}\n# or: yarn add file:./${opts.pkgName}\n\`\`\`\n\n## Use\n\n\`\`\`tsx\nimport { ${pascalCase(icons[0]?.name ?? 'Example')}Icon } from '${opts.pkgName}';\n\nexport default function App() {\n  return <${pascalCase(icons[0]?.name ?? 'Example')}Icon size={32} />;\n}\n\`\`\`\n\nEach component accepts \`size\` (number, default 24) and \`className\`.\n\n## Style\n\n\`${style}\`\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}Icon\``).join('\n')}\n`,
  });

  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          module: 'ESNext',
          moduleResolution: 'Bundler',
          jsx: 'react-jsx',
          strict: true,
          declaration: true,
          esModuleInterop: true,
          skipLibCheck: true,
        },
        include: ['src'],
      },
      null,
      2,
    ) + '\n',
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── Vue ───────────────────────────────────────────────────────────────────
function buildVue(icons: IconInput[], style: string): PackageOutput {
  const rootDir = `icon-forge-vue-${style}`;
  const files: PackageFile[] = [];
  const exports: string[] = [];

  for (const icon of icons) {
    const compName = pascalCase(icon.name) + 'Icon';
    const filename = `${compName}.vue`;
    files.push({
      path: `src/${filename}`,
      content: `<!-- Generated by Icon Forge. Style: ${style}. -->\n` +
        FRAMEWORK_BY_ID.vue.generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
    exports.push(`export { default as ${compName} } from './${compName}.vue';`);
  }

  files.push({
    path: 'src/index.ts',
    content: bannerComment('index.ts', style) + exports.join('\n') + '\n',
  });

  files.push({
    path: 'package.json',
    content: JSON.stringify(
      {
        name: rootDir,
        version: PACKAGE_VERSION,
        description: `Icon Forge Vue 3 icons (${style})`,
        license: PACKAGE_LICENSE,
        main: './src/index.ts',
        types: './src/index.ts',
        files: ['src'],
        peerDependencies: { vue: '^3.0.0' },
        keywords: ['icons', 'vue', 'svg', 'icon-forge', style],
      },
      null,
      2,
    ) + '\n',
  });

  files.push({
    path: 'README.md',
    content: `# ${rootDir}\n\nIcon Forge Vue 3 icon set (style: \`${style}\`).\n\n## Install\n\n\`\`\`bash\nnpm install ./${rootDir}\n\`\`\`\n\n## Use\n\n\`\`\`vue\n<script setup lang="ts">\nimport { ${pascalCase(icons[0]?.name ?? 'Example')}Icon } from '${rootDir}';\n</script>\n\n<template>\n  <${kebabCase(pascalCase(icons[0]?.name ?? 'Example'))}-icon :size="32" />\n</template>\n\`\`\`\n\nProp: \`size\` (number, default 24).\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}Icon\``).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── Svelte ────────────────────────────────────────────────────────────────
function buildSvelte(icons: IconInput[], style: string): PackageOutput {
  const rootDir = `icon-forge-svelte-${style}`;
  const files: PackageFile[] = [];
  const exports: string[] = [];

  for (const icon of icons) {
    const compName = pascalCase(icon.name) + 'Icon';
    const filename = `${compName}.svelte`;
    files.push({
      path: `src/${filename}`,
      content: `<!-- Generated by Icon Forge. Style: ${style}. -->\n` +
        FRAMEWORK_BY_ID.svelte.generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
    exports.push(`export { default as ${compName} } from './${compName}.svelte';`);
  }

  files.push({
    path: 'src/index.ts',
    content: bannerComment('index.ts', style) + exports.join('\n') + '\n',
  });

  files.push({
    path: 'package.json',
    content: JSON.stringify(
      {
        name: rootDir,
        version: PACKAGE_VERSION,
        description: `Icon Forge Svelte icons (${style})`,
        license: PACKAGE_LICENSE,
        svelte: './src/index.ts',
        main: './src/index.ts',
        files: ['src'],
        peerDependencies: { svelte: '>=4' },
        keywords: ['icons', 'svelte', 'svg', 'icon-forge', style],
      },
      null,
      2,
    ) + '\n',
  });

  files.push({
    path: 'README.md',
    content: `# ${rootDir}\n\nIcon Forge Svelte icon set (style: \`${style}\`).\n\n## Install\n\n\`\`\`bash\nnpm install ./${rootDir}\n\`\`\`\n\n## Use\n\n\`\`\`svelte\n<script lang="ts">\n  import { ${pascalCase(icons[0]?.name ?? 'Example')}Icon } from '${rootDir}';\n</script>\n\n<${pascalCase(icons[0]?.name ?? 'Example')}Icon size={32} />\n\`\`\`\n\nProp: \`size\` (number, default 24).\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}Icon\``).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── Angular ───────────────────────────────────────────────────────────────
function buildAngular(icons: IconInput[], style: string): PackageOutput {
  const rootDir = `icon-forge-angular-${style}`;
  const files: PackageFile[] = [];
  const exports: string[] = [];

  for (const icon of icons) {
    const compClass = pascalCase(icon.name) + 'IconComponent';
    const fileBase = `${kebabCase(icon.name)}-icon.component`;
    files.push({
      path: `src/${fileBase}.ts`,
      content: bannerComment(`${fileBase}.ts`, style) +
        FRAMEWORK_BY_ID.angular.generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
    exports.push(`export { ${compClass} } from './${fileBase}';`);
  }

  files.push({
    path: 'src/index.ts',
    content: bannerComment('index.ts', style) + exports.join('\n') + '\n',
  });

  files.push({
    path: 'package.json',
    content: JSON.stringify(
      {
        name: rootDir,
        version: PACKAGE_VERSION,
        description: `Icon Forge Angular icons (${style})`,
        license: PACKAGE_LICENSE,
        main: './src/index.ts',
        types: './src/index.ts',
        files: ['src'],
        peerDependencies: {
          '@angular/core': '>=17',
          '@angular/common': '>=17',
          '@angular/platform-browser': '>=17',
        },
        keywords: ['icons', 'angular', 'svg', 'icon-forge', style],
      },
      null,
      2,
    ) + '\n',
  });

  const sample = pascalCase(icons[0]?.name ?? 'Example');
  files.push({
    path: 'README.md',
    content: `# ${rootDir}\n\nIcon Forge Angular icon set (style: \`${style}\`).\n\n## Install\n\n\`\`\`bash\nnpm install ./${rootDir}\n\`\`\`\n\n## Use\n\n\`\`\`ts\nimport { Component } from '@angular/core';\nimport { ${sample}IconComponent } from '${rootDir}';\n\n@Component({\n  standalone: true,\n  imports: [${sample}IconComponent],\n  template: \`<${kebabCase(sample)}-icon [size]="32"></${kebabCase(sample)}-icon>\`,\n})\nexport class AppComponent {}\n\`\`\`\n\nInput: \`size\` (number, default 24).\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}IconComponent\` (\`<${kebabCase(i.name)}-icon>\`)`).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── React Native ──────────────────────────────────────────────────────────
function buildReactNative(icons: IconInput[], style: string): PackageOutput {
  const rootDir = `icon-forge-rn-${style}`;
  const files: PackageFile[] = [];
  const exports: string[] = [];

  for (const icon of icons) {
    const compName = pascalCase(icon.name) + 'Icon';
    const filename = `${compName}.tsx`;
    files.push({
      path: `src/${filename}`,
      content: bannerComment(filename, style) +
        FRAMEWORK_BY_ID['react-native'].generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
    exports.push(`export { default as ${compName} } from './${compName}';`);
  }

  files.push({
    path: 'src/index.ts',
    content: bannerComment('index.ts', style) + exports.join('\n') + '\n',
  });

  files.push({
    path: 'package.json',
    content: JSON.stringify(
      {
        name: rootDir,
        version: PACKAGE_VERSION,
        description: `Icon Forge React Native icons (${style})`,
        license: PACKAGE_LICENSE,
        main: './src/index.ts',
        types: './src/index.ts',
        files: ['src'],
        peerDependencies: { react: '>=18', 'react-native': '>=0.70', 'react-native-svg': '>=13' },
        keywords: ['icons', 'react-native', 'svg', 'icon-forge', style],
      },
      null,
      2,
    ) + '\n',
  });

  const sample = pascalCase(icons[0]?.name ?? 'Example');
  files.push({
    path: 'README.md',
    content: `# ${rootDir}\n\nIcon Forge React Native icon set (style: \`${style}\`).\n\n## Install\n\n\`\`\`bash\nnpm install ./${rootDir} react-native-svg\n\`\`\`\n\n## Use\n\n\`\`\`tsx\nimport { ${sample}Icon } from '${rootDir}';\n\nexport default function App() {\n  return <${sample}Icon size={32} />;\n}\n\`\`\`\n\nProp: \`size\` (number, default 24).\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}Icon\``).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── Flutter ───────────────────────────────────────────────────────────────
function buildFlutter(icons: IconInput[], style: string): PackageOutput {
  const rootDir = `icon_forge_${style.replace(/-/g, '_')}`;
  const files: PackageFile[] = [];
  const exports: string[] = [];

  for (const icon of icons) {
    const fileBase = snakeCase(icon.name) + '_icon';
    files.push({
      path: `lib/src/${fileBase}.dart`,
      content: `// Generated by Icon Forge. Style: ${style}. License: ${PACKAGE_LICENSE}.\n` +
        FRAMEWORK_BY_ID.flutter.generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
    exports.push(`export 'src/${fileBase}.dart';`);
  }

  files.push({
    path: `lib/${rootDir}.dart`,
    content: `// Generated by Icon Forge. Style: ${style}.\nlibrary ${rootDir};\n\n${exports.join('\n')}\n`,
  });

  files.push({
    path: 'pubspec.yaml',
    content:
`name: ${rootDir}
description: "Icon Forge Flutter icons (${style}) — auto-generated."
version: ${PACKAGE_VERSION}

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
`,
  });

  const sample = pascalCase(icons[0]?.name ?? 'Example');
  files.push({
    path: 'README.md',
    content: `# ${rootDir}\n\nIcon Forge Flutter icon set (style: \`${style}\`).\n\n## Install (local path)\n\nIn your project's \`pubspec.yaml\`:\n\n\`\`\`yaml\ndependencies:\n  ${rootDir}:\n    path: ./${rootDir}\n\`\`\`\n\nThen \`flutter pub get\`.\n\n## Use\n\n\`\`\`dart\nimport 'package:${rootDir}/${rootDir}.dart';\n\nclass MyWidget extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return ${sample}Icon(size: 32);\n  }\n}\n\`\`\`\n\nParameter: \`size\` (double, default 24).\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}Icon\``).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── SwiftUI ───────────────────────────────────────────────────────────────
function buildSwiftUI(icons: IconInput[], style: string): PackageOutput {
  const moduleName = 'IconForge' + pascalCase(style);
  const rootDir = `IconForge-${style}`;
  const files: PackageFile[] = [];

  for (const icon of icons) {
    const compName = pascalCase(icon.name) + 'Icon';
    const filename = `${compName}.swift`;
    files.push({
      path: `Sources/${moduleName}/${filename}`,
      content: `// Generated by Icon Forge. Style: ${style}. License: ${PACKAGE_LICENSE}.\n` +
        FRAMEWORK_BY_ID.swiftui.generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
  }

  files.push({
    path: 'Package.swift',
    content:
`// swift-tools-version:5.7
import PackageDescription

let package = Package(
    name: "${moduleName}",
    platforms: [
        .iOS(.v15),
        .macOS(.v12),
    ],
    products: [
        .library(name: "${moduleName}", targets: ["${moduleName}"]),
    ],
    dependencies: [
        .package(url: "https://github.com/SVGKit/SVGKit", from: "3.0.0"),
    ],
    targets: [
        .target(
            name: "${moduleName}",
            dependencies: [
                .product(name: "SVGKit", package: "SVGKit"),
            ],
            path: "Sources/${moduleName}"
        ),
    ]
)
`,
  });

  const sample = pascalCase(icons[0]?.name ?? 'Example');
  files.push({
    path: 'README.md',
    content: `# ${moduleName}\n\nIcon Forge SwiftUI icon set (style: \`${style}\`).\n\n## Install (Swift Package Manager, local path)\n\nIn Xcode: File → Add Package Dependencies → Add Local… → choose this folder.\n\nOr in your \`Package.swift\`:\n\n\`\`\`swift\n.package(path: "./${rootDir}")\n\`\`\`\n\n## Use\n\n\`\`\`swift\nimport SwiftUI\nimport ${moduleName}\n\nstruct ContentView: View {\n    var body: some View {\n        ${sample}Icon(size: 32)\n    }\n}\n\`\`\`\n\nParameter: \`size\` (CGFloat, default 24).\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}Icon\``).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── Kotlin (Compose) ──────────────────────────────────────────────────────
function buildKotlin(icons: IconInput[], style: string): PackageOutput {
  const rootDir = `icon-forge-kotlin-${style}`;
  const files: PackageFile[] = [];

  for (const icon of icons) {
    const compName = pascalCase(icon.name) + 'Icon';
    const filename = `${compName}.kt`;
    files.push({
      path: `src/main/kotlin/com/iconforge/${filename}`,
      content: `// Generated by Icon Forge. Style: ${style}. License: ${PACKAGE_LICENSE}.\n` +
        FRAMEWORK_BY_ID.kotlin.generate({ name: icon.name, svg: icon.svg, size: 24 }),
    });
  }

  files.push({
    path: 'build.gradle.kts',
    content:
`plugins {
    id("com.android.library") version "8.4.0"
    id("org.jetbrains.kotlin.android") version "1.9.23"
}

android {
    namespace = "com.iconforge"
    compileSdk = 34
    defaultConfig { minSdk = 24 }
    buildFeatures { compose = true }
    composeOptions { kotlinCompilerExtensionVersion = "1.5.13" }
}

dependencies {
    implementation("androidx.compose.ui:ui:1.6.7")
    implementation("androidx.compose.foundation:foundation:1.6.7")
    implementation("io.coil-kt:coil-compose:2.6.0")
    implementation("io.coil-kt:coil-svg:2.6.0")
}
`,
  });

  files.push({
    path: 'settings.gradle.kts',
    content: `rootProject.name = "${rootDir}"\n`,
  });

  const sample = pascalCase(icons[0]?.name ?? 'Example');
  files.push({
    path: 'README.md',
    content: `# ${rootDir}\n\nIcon Forge Kotlin/Compose icon set (style: \`${style}\`).\n\n## Install (Gradle composite build, local path)\n\nIn your root project's \`settings.gradle.kts\`:\n\n\`\`\`kotlin\nincludeBuild("./${rootDir}")\n\`\`\`\n\n## Use\n\n\`\`\`kotlin\nimport com.iconforge.${sample}Icon\n\n@Composable\nfun MyScreen() {\n    ${sample}Icon(sizeDp = 32)\n}\n\`\`\`\n\nParameter: \`sizeDp\` (Int, default 24).\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${pascalCase(i.name)}Icon\``).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── HTML / CSS ────────────────────────────────────────────────────────────
function buildHtml(icons: IconInput[], style: string): PackageOutput {
  const rootDir = `icon-forge-html-${style}`;
  const files: PackageFile[] = [];
  const symbols: string[] = [];

  for (const icon of icons) {
    const slug = kebabCase(icon.name);
    files.push({
      path: `icons/${slug}.svg`,
      content: icon.svg,
    });
    // Extract inner content for sprite symbol.
    const inner = icon.svg.replace(/^[\s\S]*?<svg[^>]*>([\s\S]*?)<\/svg>\s*$/i, '$1');
    const vbMatch = icon.svg.match(/viewBox=["']([^"']+)["']/i);
    const viewBox = vbMatch ? vbMatch[1] : '0 0 24 24';
    symbols.push(`  <symbol id="if-${slug}" viewBox="${viewBox}">${inner}</symbol>`);
  }

  files.push({
    path: 'sprite.svg',
    content: `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join('\n')}\n</svg>\n`,
  });

  files.push({
    path: 'index.html',
    content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Icon Forge — ${style}</title>
  <style>
    body { background: #09090b; color: #fafafa; font-family: system-ui; padding: 2rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); gap: 1rem; }
    .card { display: flex; flex-direction: column; align-items: center; padding: 1rem; background: #18181b; border: 1px solid #3f3f46; border-radius: 0.5rem; }
    .card svg { width: 48px; height: 48px; color: #fafafa; }
    .name { font-size: 0.75rem; margin-top: 0.5rem; color: #a1a1aa; }
  </style>
</head>
<body>
  <h1>Icon Forge — ${style} (${icons.length} icons)</h1>
  <p>Use any icon via inline SVG, the <code>sprite.svg</code> sprite + &lt;use&gt;, or as a CSS background.</p>
  <div class="grid">
${icons.map((i) => `    <div class="card"><svg><use href="sprite.svg#if-${kebabCase(i.name)}" /></svg><div class="name">${i.name}</div></div>`).join('\n')}
  </div>
</body>
</html>
`,
  });

  files.push({
    path: 'README.md',
    content: `# ${rootDir}\n\nIcon Forge HTML/CSS icon set (style: \`${style}\`).\n\n## Files\n\n- \`icons/<name>.svg\` — one SVG file per icon\n- \`sprite.svg\` — combined sprite for \`<use href="sprite.svg#if-<name>">\`\n- \`index.html\` — preview gallery\n\n## Use\n\n### Inline\n\n\`\`\`html\n<img src="icons/${kebabCase(icons[0]?.name ?? 'example')}.svg" width="32" height="32" />\n\`\`\`\n\n### Sprite + \`<use>\`\n\n\`\`\`html\n<svg width="32" height="32"><use href="sprite.svg#if-${kebabCase(icons[0]?.name ?? 'example')}" /></svg>\n\`\`\`\n\n## Icons (${icons.length})\n\n${icons.map((i) => `- \`${kebabCase(i.name)}.svg\` → \`#if-${kebabCase(i.name)}\``).join('\n')}\n`,
  });

  return { rootDir, files, archiveName: `${rootDir}.zip` };
}

// ─── Dispatcher ────────────────────────────────────────────────────────────
export const PACKAGE_BUILDERS: Record<
  FrameworkId,
  (icons: IconInput[], style: string) => PackageOutput
> = {
  react: (icons, style) =>
    buildReact(icons, style, {
      withUseClient: false,
      nameSuffix: '',
      pkgName: `icon-forge-react-${style}`,
      description: `Icon Forge React icons (${style})`,
    }),
  nextjs: (icons, style) =>
    buildReact(icons, style, {
      withUseClient: true,
      nameSuffix: '',
      pkgName: `icon-forge-nextjs-${style}`,
      description: `Icon Forge Next.js icons (${style}) — client components`,
    }),
  vue: buildVue,
  svelte: buildSvelte,
  angular: buildAngular,
  'react-native': buildReactNative,
  flutter: buildFlutter,
  swiftui: buildSwiftUI,
  kotlin: buildKotlin,
  html: buildHtml,
};

export function getFrameworkLabel(id: FrameworkId): string {
  const f: Framework | undefined = FRAMEWORK_BY_ID[id];
  return f?.label ?? id;
}
